### ISSUE TITLE
Error during show_cad()

### ISSUE THREAD

**Issue by DrPlamsa** [Fusion-Power-Plant-Framework/bluemira#1020]
## Describe the bug

When running the `EUDEMO_reactor.py` example file, I get an error that starts with `show_cad()` and gets traced through freeCAD and pivy.

## Steps to reproduce

Steps to reproduce the behaviour:

1. I cd'd into directory `examples/design/EU-DEMO`
2. I ran command `python EUDEMO_reactor.py`
3. I closed the 2D equilibrium plot and two 2D plasma plots
4. An error occurred in the terminal and the run terminated

## Expected behaviour

A CAD render should pop up for me to view the plasma

## Screenshots / Tracebacks

```
Traceback (most recent call last):
  File "EUDEMO_reactor.py", line 407, in <module>
    plasma.get_component("xyz").show_cad()
  File "/home/cswan/bluemira/bluemira/display/displayer.py", line 279, in show_cad
    return self._displayer.show_cad(self, **kwargs)
  File "/home/cswan/bluemira/bluemira/display/displayer.py", line 234, in show_cad
    show_cad(self._shapes, self._options, **kwargs)
  File "/home/cswan/bluemira/bluemira/display/displayer.py", line 172, in show_cad
    cadapi.show_cad(shapes, freecad_options)
  File "/home/cswan/bluemira/bluemira/codes/_freecadapi.py", line 1721, in show_cad
    viewer = quarter.QuarterWidget()
  File "/home/cswan/miniforge3/envs/bluemira/lib/python3.8/site-packages/pivy/quarter/QuarterWidget.py", line 227, in __init__
    sostatemachine = coin.cast(statemachine, "SoScXMLStateMachine")
SystemError: <built-in function cast> returned NULL without setting an error

```

## Environment (please complete the following information)

- OS: Ubuntu 20.04.4 LTS
- Branch: develop

## Additional context

I beg lenience; this is my first foray into BLUEMIRA and I may have made mistakes during installation or use.

**Comment by je-cook** [comment]
Hi Charles. We (well @ivanmaione) have found a fix, if you run the below commands to activate your bluemira python environment and downgrade pivy your CAD viewer should work again:

```bash
source ~/.miniforge-init.sh
conda activate bluemira
conda install pivy=0.6.5 -n bluemira
```

Thanks for the bug report, this issue will automatically close on the merge of #1048
