### ISSUE TITLE
Spurious printing of `StopIteration` in IPython

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#1025]
## Describe the bug

We get these now:
```
| EQUILIBRIA G-S iter 0: relative delta_psi: 39.51 %                      |
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
StopIteration: 
| EQUILIBRIA G-S iter 1: relative delta_psi: 25.45 %                      |
```
They aren't errors, they are just red text that does nothing.

Only seen in IPython since I updated my environment today.

## Steps to reproduce

Run an equilibrium example and observe

Steps to reproduce the behaviour:

1. Run examples/equilibria/eudemo_2017.py
2. Run command '...'
3. Note output '...'
4. See error '...'

## Screenshots / Tracebacks

If applicable, add screenshots / tracebacks to help explain your problem.

## Environment (please complete the following information)

- OS: [e.g. Ubuntu 18.04]
- Version [e.g. 0.0.x]
- Branch (if developing) [e.g. develop]

**Comment by CoronelBuendia** [comment]
I'm starting to see these in a normal Python console too... sad times!

![image](https://user-images.githubusercontent.com/26097289/189308299-bd7a86bb-1fe1-4727-9948-7d8a635c171c.png)

**Comment by je-cook** [comment]
I've been down a couple of rabbit holes to try and fix this. I still don't really get where the printing even happens (it doesnt seem to be explicit)

**Comment by hsaunders1904** [comment]
https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app 

https://docs.python.org/3/whatsnew/3.7.html#changes-in-python-behavior

**Comment by je-cook** [comment]
this has stopped happening for me locally havent tried to pinpoint when
