### ISSUE TITLE
Untracked files after tests are run

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#1040]
## Describe the bug

After running the test suite, there are a bunch of files outputted that aren't ignored/cleaned up. 

To avoid me accidentally committing one of these, we should ignore/clean them up.

The modified/untracked files are:

```txt
modified:   examples/mesh/mesh_tutorial.ipynb

Untracked files:
        Mesh_linkfile.json
        examples/mesh/Mesh_linkfile.json
        tests/codes/process/test_generated_data/IN.DAT
```

## Steps to reproduce

Run the full test suite (I'm not sure if you need to add the flags to get all, or some, of the extra files), then run `git status -uall`.

## Expected behaviour

There should be no untracked/modified files in Git after the test suite is run.

**Comment by je-cook** [comment]
`git clean -ix` will give you a full list inc gitignored files (before it asks whether you want to clean anything)
