### ISSUE TITLE
`DisjointedFace` error erroneously raised

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#1045]
## Describe the bug

I occasionally get `DisjointedFace` errors which I'm fairly confident are false positives.

e.g. 
![image](https://user-images.githubusercontent.com/26097289/167844520-355c7bf7-562b-4920-b124-1614a988ed12.png)
It's possible that the orientation of the wires is wrong, as they are both born in this case from offset operations. But the fact that this only sometimes happens points to some weirdness.

Also, I'm pretty sure it is only happening on our end, i.e. during reconstruction of the Matryoshka.

## Steps to reproduce

Steps to reproduce the behaviour:

On #980 run EUDEMO reactor several times until you get it..

## Screenshots / Tracebacks

If applicable, add screenshots / tracebacks to help explain your problem.

## Environment (please complete the following information)

- OS: [e.g. Ubuntu 18.04]
- Version [e.g. 0.0.x]
- Branch (if developing) [e.g. develop]

**Comment by je-cook** [comment]
I have a feeling this could have a similar route cause to the pivy pinning issue from the CAD viewer. Today after wiping my env to test that fix is the first time I've seen this error.

**Comment by hsaunders1904** [comment]
See https://github.com/Fusion-Power-Plant-Framework/bluemira/pull/1079#pullrequestreview-980315716 for some geometry that may be useful in replicating the issue

**Comment by CoronelBuendia** [comment]
I've just checked the example that was failing before, and can confirm it no longer comes up.
