### ISSUE TITLE
Improve design/documentation of slice_shape

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#1050]
## Description of issue / requirement to address

I'm a little confused about the API of [`bluemira.geometry.tools.slice_shape`](https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/07e6d83705597a15410705a158d87e9c2ada5e2d/bluemira/geometry/tools.py#L774).

The docstring suggests that the function returns a tuple, but I think what it means is, _if the input is a wire it returns x, if the input is one of these other geoms, then return y_. I'm not really sure.

Also, we may wish to consider the name, the function isn't actually _slicing_ anything. It's finding the intersections between a shape and a plane. 

## Proposed solution

I'm not a big fan of functions returning multiple types. It puts a lot of burden on the caller to check their outputs after the call. I propose to split the function up into separate functions, where each one only returns a single type. So we may end up with something like:

```python
def split_wire(wire: BluemiraWire, plane: BluemiraPlane) -> np.ndarray:
    ...

def split_face(face: BluemiraFace, plane: BluemiraPlane) -> BluemiraWire:
   ...

def split_shape_3d(shape: Union[BluemiraSolid, BluemiraShell], plane: BluemiraPlane) -> List[BluemiraWire]:
   ...
```

If the plane does not intercept the shape, we could potentially return `None` (make the return type `Optional`), but I would tend to prefer raising an error; EAFP over LBYL.

## Alternative solutions

We stick with the current `slice_shape` but we document more clearly what the inputs/outputs are. This still shifts the burden to the caller to check their inputs/outputs when using the function, which, in a public API, I would find not great.

**Comment by oliverfunk** [comment]
After speaking @CoronelBuendia, I have concluded that although this is a good idea/suggestion, it would require a non-trivial refactor of a lot of code and necessarily introduce a simplified API.

Additionally, there will still be unavoidable complexity in the return types.
If you are slicing a face with a plane, you can get a single point or a line. There is no way around that.

The return type would still need to be a union of types.

This is, therefore not a worthwhile pursuit right now.
