### ISSUE TITLE
Additionnal line on CAD viewer after slice operation

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#1071]
## Describe the bug

Some additionnal lines appears on the FreeCAD viewer after slice operation. I am not sure if this is a bug in the viewer itself or there real consequences on the geometry.

This line addition remains even if we use a `deepcopy` in the original Solid to make the operation, which is difficult to understand.

Geometry without the slice operation:
![image](https://user-images.githubusercontent.com/55831357/169016310-444895cd-7e8a-4273-b0dc-650ab6c7bcb6.png)

Geometry with the slice operation without `deepcopy`:
![image](https://user-images.githubusercontent.com/55831357/169016969-1f03d57e-a061-4343-8583-710ee2b53859.png)

Geometry with the slice operation and the `deepcopy` (same issue):
![image](https://user-images.githubusercontent.com/55831357/169017380-ce3218ad-6152-470c-9040-0e75470b1ba4.png)

## Steps to reproduce

Steps to reproduce the behaviour:
1. Make a solid
2. slice it
3. see it

## Expected behaviour

No additionnal lines to appear on the CAD viewer

## Additional context

Shapes with additionnal lines to be opened with `qbit` or `spaceclaim` to check if the lines are genuine

**Comment by CoronelBuendia** [comment]
It's possible it's environment related... I have not updated my conda in quite some time.

**Comment by CoronelBuendia** [comment]
It's possible it's environment related... I have not updated my conda in quite some time.

**Comment by je-cook** [comment]
I dont see them either and I updated mine yesterday

**Comment by je-cook** [comment]
Could you send a minimal code snippet that reproduces the bug?

**Comment by CoronelBuendia** [comment]
@sebkahn can you confirm that this is not an issue and that actually #1108 is the problem?

**Comment by sebkahn** [comment]
> @sebkahn can you confirm that this is not an issue and that actually #1108 is the problem?

These are two probems. 
This issue is probably a CAD viewer issue, 1108 is a genuine feature.

**Comment by CoronelBuendia** [comment]
we don't see this problem. please run the lines above on your end and confirm

**Comment by CoronelBuendia** [comment]
confirmed by @sebkahn as not being a problem (for this simple case). MWE should possibly include hollow solids and/or solids created by a sweep_shape operation

**Comment by CoronelBuendia** [comment]
Alright, so I've finally got round to checking this with a tougher example (hollow swept solid with a mixture of splines and straights).

I don't see any ghost lines. I'm closing.

```python
import numpy as np
from bluemira.geometry.tools import *
from bluemira.geometry.parameterisations import PrincetonD
from bluemira.geometry.plane import BluemiraPlane
from bluemira.display import show_cad
from bluemira.display.displayer import DisplayCADOptions

p = PrincetonD().create_shape({"x1": {"value": 3}})

xs = make_polygon({"x": [-0.5, 0.5, 0.5, -0.5], "y": [-0.5, -0.5, 0.5, 0.5]}, closed=True)
xs.translate((3, 0,0))
xs_in = offset_wire(xs, -0.05)
result = sweep_shape(xs, p)
result2 = sweep_shape(xs_in, p)

final = boolean_cut(result, result2)[0]
xz_plane = BluemiraPlane(axis=(0, 1, 0))

final = boolean_cut(result, result2)[0]

_ = slice_shape(final, xz_plane)

show_cad(final, DisplayCADOptions(transparency=0.5))
```

![image](https://user-images.githubusercontent.com/26097289/225909546-08ebeea6-87a7-4204-8baf-07f4e204bd11.png)
