### ISSUE TITLE
EU-DEMO example is not a good externally facing example file

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#1073]
## Description of issue / requirement to address

The configuration and parameter is confusing and not a recommended use case.

The `reactor.run()` method does not expose the logic of the design and build sequence in a clear way.

The example does too much, is too specific to EU-DEMO and is not a good entry point for a new user.

## Proposed solution

Move the EUDEMO example to a separate folder, along with #1195 
Make a new simple example file showing how to make a reactor design, showing aspect of configuration, design optimisation. components, etc. for a new user "minimum workflow"

## Additional context

It may be that we need a separate script for our own purposes (but perhaps this should not live in the examples)

**Comment by je-cook** [comment]
the current EUDEMO example will be removed in #1536 needs to be readded (see #1523)

**Comment by hsaunders1904** [comment]
I've started re-writing the EUDEMO build with the new builder/desinger architecture in [hsaunders1904/eudemo_reactor](https://github.com/Fusion-Power-Plant-Framework/bluemira/tree/hsaunders1904/eudemo_reactor). Work on this branch is on hold at the moment, but this is where we can pick up from in the 1.0.0 milestone.
