### ISSUE TITLE
EU-DEMO tree structure decision

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#1076]
## Description of issue / requirement to address

We need to follow a clear and documented way of structuring the `Component` tree for an EU-DEMO reactor. And do so consistently.

There are two obvious choices:

* Have xy, xz, xyz at the base `Component` level
* Have each sub-component have xy, xz, and xyz nodes

There are implications of this choice, both in terms of implementation, and the ability to instantiate `Component` outside of a `Reactor`

## Proposed solution

We should discuss the pros and cons in the workshop, make a decision, and implement it.
@ivanmaione as discussed

**Comment by je-cook** [comment]
As of writing each builder makes its own xz xy and xyz nodes for the component being built. This is therefore the default. 

If the alternative is desired a function to move nodes about could live in the reactor manager object

**Comment by je-cook** [comment]
Its possible that we could just add a method to the `Reactor` base object so that we can have the best of both wrolds using symlinks with https://anytree.readthedocs.io/en/latest/api/anytree.node.html#anytree.node.symlinknode.SymlinkNode
