### ISSUE TITLE
Add a `GEOMETRY_TOLERANCE` or similar and use for treatment of geometry 

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#1084]
## Description of issue / requirement to address

FreeCAD's tolerance is of 1e-7 and we often use EPS in geometry in bluemira, which is much smaller than this and designed really for machine precision.

## Proposed solution

We should use a tolerance for geometry more consistent with that of FreeCAD. This has come in the context of checking for closed wires and coordinates, but is likely to be relevant elsewhere too.

**Comment by je-cook** [comment]
Sounds reasonable, do we know if its hard coded to `1e-7` or just a 32 bit number?:

```python
In [22]: np.finfo(np.float32).eps
Out[22]: 1.1920929e-07
```

**Comment by OceanNuclear** [comment]
I think @CoronelBuendia is referring to the default tolerance which is set to exactly 1.0E-7 from what I can find online
