### ISSUE TITLE
Convert BLUEPRINT 3D CAD to use bluemira objects

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#109]
**Is your feature request related to a problem? Please describe.**
BLUEPRINT 3D CAD is still built using OCC.

**Describe the solution you'd like**
We should convert this to use bluemira objects.

**Describe alternatives you've considered**
N/A

**Comment by CoronelBuendia** [comment]
Closing this as:
* We've rebuilt the bluemira geometry module to use primitives from scratch.
* We're going to deprecate BLUEPRINT ASAP and the transition period is coming to an end
* We're not going to redo the BLUEPRINT CAD or wrap it in the new CAD
