### ISSUE TITLE
Split out force constraint calculations into separate functions

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#1107]
## Description of issue / requirement to address

The `coil_force_constraints` function does three separate calculations. This is difficult to read easily and less modular.

## Proposed solution
Split out the three different constraints into separate functions, that are all used by the corresponding `OptimisationConstraint` class.

## Additional context

This will help when the constraints are generalised to apply to symmetric circuits

**Comment by je-cook** [comment]
Since the optimisation refactor the function (now class) in question is https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/a662f4cf3599e1c631a881f610fa58d4ff71984f/bluemira/equilibria/optimisation/constraint_funcs.py#L253

**Comment by je-cook** [comment]
Done in #3451
