### ISSUE TITLE
(Potentially) non-functionning removeSplitter

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#1108]
## Description of issue

The boolean fuse operation does not merge the following faces although `removeSplitter` is called in the `boolean_fuse` operation.

![image](https://user-images.githubusercontent.com/55831357/170980826-d99a8d5d-bbe4-43ba-b156-8d21027e9001.png)

## Reproducible example

Under progress

**Note:** It may be a issue on my script rather than a Bluemira one as it is really hard to reproduce.

Best reagards

**Comment by CoronelBuendia** [comment]
@sebkahn can you give a MWE so we can more clearly understanding the problem please?

@ivanmaione if I have understood correctly this relates to the splitter lines, which I thought we were already removing with `shape.removeSplitter()`. I remember in pythonOCC there was a `shape.refine()` call for boolean operations.

**Comment by sebkahn** [comment]
> @sebkahn can you give a MWE so we can more clearly understanding the problem please?
> 
> @ivanmaione if I have understood correctly this relates to the splitter lines, which I thought we were already removing with `shape.removeSplitter()`. I remember in pythonOCC there was a `shape.refine()` call for boolean operations.

Will try to use removeSplitter !

**Comment by CoronelBuendia** [comment]
No, no, it's already used, which is why I am confused aboutwhat you are seeing.

**Comment by sebkahn** [comment]
> @sebkahn could you please provide a very simple example to reproduce the problem? I will give a look at it. Just as info, the removeSplitter function is called in `cadapi.boolean_fuse(api_shapes)`, if you want to update the description of the issue.

Hello, thanks for taking this issue on you!

Will do ASAP the minimal example.

**Comment by CoronelBuendia** [comment]
This is a very simple example with two solids that just "touch". There is no line shown once the solids are fused. We've discussed this and we're aware this is a very simple example (where we know that the faces touch).

```python
from bluemira.geometry.tools import make_polygon, extrude_shape, boolean_fuse
from bluemira.display import show_cad

from bluemira.geometry.face import BluemiraFace

wire = make_polygon({"x": [4, 6, 6, 4], "z": [2, 2, 4, 4]}, closed=True)

face = BluemiraFace(wire)
solid = extrude_shape(face, (0, 1, 0))
solid2 = solid.deepcopy()
solid2.translate((0, 1, 0))
show_cad([solid, solid2])

result = boolean_fuse([solid, solid2])

show_cad(result)
```

It's very possible that with a more complicated pair of solids, this issue does exist. At least this MWE shows that the splitter lines are removed when we know that the faces touch. It's possible that for the picture above, the faces are not considered as touching for some reason.

**Comment by CoronelBuendia** [comment]
Again, I have tried this with a tougher example (hollow, swept solid, with mixture of splines and straights).

I do not see any ghost lines. I am closing.
```python
import numpy as np
from bluemira.geometry.tools import *
from bluemira.geometry.parameterisations import PrincetonD
from bluemira.geometry.plane import BluemiraPlane
from bluemira.display import show_cad
from bluemira.display.displayer import DisplayCADOptions
from copy import deepcopy

p = PrincetonD().create_shape({"x1": {"value": 3}})

xs = make_polygon({"x": [-0.5, 0.5, 0.5, -0.5], "y": [-0.5, -0.5, 0.5, 0.5]}, closed=True)
xs.translate((3, 0,0))
xs_in = offset_wire(xs, -0.05)
result = sweep_shape(xs, p)
result2 = sweep_shape(xs_in, p)

final = boolean_cut(result, resu
xz_plane = BluemiraPlane(axis=(0, 1, 0))

final = boolean_cut(result, result2)[0]

_ = slice_shape(final, xz_plane)

cut_face = BluemiraFace(make_polygon({"x": [0, 100, 100, 0], "z":[-100, -100, 100, 100]},closed=True))
cut_box1 = extrude_shape(cut_face, (0, 10, 0))
cut_box2 = extrude_shape(cut_face,  (0, -10, 0))

half1 = boolean_cut(deepcopy(final), cut_box1)[0]
half2 = boolean_cut(deepcopy(final), cut_box2)[0]

fused_final = boolean_fuse([half1, half2])
show_cad(fused_final)
```

![image](https://user-images.githubusercontent.com/26097289/225912790-a74172d1-096a-45a1-a833-4794259b1bee.png)
