### ISSUE TITLE
Add sector GroupingComponents

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#111]
**Is your feature request related to a problem? Please describe.**
The reactor will be built in sectors to assist with e.g. remote maintenance. These should be reflected in the component tree of the resulting reactor build.

**Describe the solution you'd like**
Add a GroupingComponent for each sector and include relevant GroupingComponents / PhysicalComponents under each sector.

**Describe alternatives you've considered**
N/A

**Comment by CoronelBuendia** [comment]
@DanShort12 we've converged to just using Components for this, right?

**Comment by DanShort12** [comment]
Yep, for now I think we just use Components rather than anything else. Could be that we need to revisit later but I suspect a new issue with more detail will be needed at that point.
