### ISSUE TITLE
Possibly broken figures with plotting-on

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#1175]
## Describe the bug

- [ ] `tests/display/test_plotter.py::TestPointsPlotter::test_plotting_2d` fig2  - empty

- [x] `tests/geometry/test_inscribed_rect.py::TestInscribedRectangle::test_inscribed_rectangle[shape3-False]`  - no shapes convering the region

- [ ] `tests/geometry/test_deprecated_tools.py::TestIntersections::test_join_intersect` fig 4 looks a bit odd

there may be others

## Steps to reproduce

Run the tests with plotting on

## Screenshots / Tracebacks

If applicable, add screenshots / tracebacks to help explain your problem.

## Environment (please complete the following information)

- OS: [e.g. Ubuntu 18.04]
- Version [e.g. 0.0.x]
- Branch (if developing) [e.g. develop]

**Comment by CoronelBuendia** [comment]
Closing this as the last test no longer exists and the first one no longer plots an empty figure on develop (there is only one figure)
