### ISSUE TITLE
Develop initial structure for Power Cycle module

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#1228]
## Description of issue / requirement to address
BLUEMIRA should boast of a power balance calculation to compute the net electricity produced by the plant. As a first approach to this issue, an initial module should be implemented to house all of the essential calculations with this aim.

## Proposed solution
For consistency, the module should be named Power Cycle (analogously to the Fuel Cycle), and should include two internal routines:
- Recirculating Power Loads, that identifies the electrical power consumed by the plant
- Balance-of-Plant, that identifies the power produced by the plant

A master manager class should retrieve the calculations of each sub-module and perform the subtraction, to compute the net power produced by the plant.
Inputs could be retrieved from a file or implemented directly in a builder class.

## Additional context
The module should incorporate some features of the old BLUEPRINT code, such as visualization through a power flow diagram.

**Comment by je-cook** [comment]
Completed in #2873
