### ISSUE TITLE
Develop classes to build a pulse timeline for the Power Cycle

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#1243]
## Description of issue / requirement to address
The Power Cycle aims at simulating a complete reactor pulse. Classes should be created to represent a generic scenario, that can used to organize the Power Cycle simulation in different pulses, each composed of different phases.

## Proposed solution
Create 3 classes to organize :
- `PowerCyclePhase` (shortest temporal period with unified characteristics for Power Cycle simulations)
- `PowerCyclePulse` (collection of phases)
- `PowerCycleScenario` (collection of pulses)
- `ScenarioBuilder` (creates a `PowerCycleScenario` instance from a `json` input file)

## Additional context
Phases will be classified as 'steady-state' or 'transient' in a subclass (namely, `BOPPhase`), for later implementation of a time-dependent Balance-of-Plant model for the Power Cycle.

**Comment by je-cook** [comment]
Completed in #2873
