### ISSUE TITLE
Develop classes to represent power loads produced/consumed in the Power Cycle

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#1244]
## Description of issue / requirement to address
The main calculations performed by the Power Cycle should be done in terms of time-dependent power loads. These power loads should be constructed from simple power requirement information and expected time-dependent behavior (e.g. 'ramp' or 'step').

## Proposed solution
Development of 4 classes to build power loads to be used in the Power Cycle module:
- `LoadData` (building blocks for `PowerLoad`, validates basic inputs before building them)
- `PowerLoad` (computes a time-dependent power curve based on expected behavior -- an interpolation model)
- `PhaseLoad` (set of power loads that represent the power consumption/production during a given phase, which can be normalized in time or not)
- `PulseLoad` (set of phase loads that are shifted in time to build a power curve during a pulse)

## Additional context
Phase and Pulse specifications dependent on timeline classes (#1243).

**Comment by je-cook** [comment]
Completed in #2873
