### ISSUE TITLE
Develop base classes and tools for Power Cycle module

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#1245]
## Description of issue / requirement to address
Many classes in the Power Cycle module present some common characteristics that can be shared by Abstract Base Classes (ABC).
Functions developed for convenience that are used by more than one class should be stand-alone for later re-location in bluemira.

## Proposed solution
Implement a `base` script that includes ABC classes for the Power Cycle module.
Implement a `tools` script with stand-alone functions to be used as convenience tools.

**Comment by je-cook** [comment]
Completed in #2873
