### ISSUE TITLE
Develop Power Cycle consumption sub-module

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#1246]
## Description of issue / requirement to address
The Power Cycle module should include a sub-routine to sum all power consumption contributions in the power plant, to be passed to a Power Cycle manager class.

## Proposed solution
Implement a sub-module named Recirculating Power Loads, that creates all power consumption power loads.

**Comment by je-cook** [comment]
Completed in #2873
