### ISSUE TITLE
Develop Power Cycle production sub-module

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#1247]
## Description of issue / requirement to address
The Power Cycle module should include a sub-routine to compute the power loads associated with the Balance-of-Plant system of the power plant, to be passed to a Power Cycle manager class.

## Proposed solution
Implement a sub-module named Balance-of-Plant, that creates all associated power loads.

**Comment by je-cook** [comment]
Completed in #2873
