### ISSUE TITLE
Develop a Power Cycle manager class to compute net electricity

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#1248]
## Description of issue / requirement to address
To compute net electricity, the Power Cycle module should have a high-level manager class that creates power loads based on run inputs defined by `json` files. This manager class should taken into consideration 3 types of plant loads: active (consumption) loads, reactive (consumption) loads and production loads.
The class should build a net pulse load by subtracting active load from production loads.

## Proposed solution
Create a `PowerCycleManager` class.

**Comment by je-cook** [comment]
Completed in #2873
