### ISSUE TITLE
Plotting test helper functions

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#1320]
## Description of issue / requirement to address

Add a helper for plotting during tests to deal with creating and closing a figure so the tests work without having an interactive backend.

## Proposed solution

Create some helper classes

## Alternative solutions

Do nothing and make people close their plots

## Additional context

#740

**Comment by CoronelBuendia** [comment]
@je-cook I believe this works now, no?

**Comment by je-cook** [comment]
What we currently do works but we havent made a helper function so you dont have to remember to write a load of things in setup and teardown methods
