### ISSUE TITLE
Topological Naming - the root cause of most CAD and geometry issues

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#1347]
## Describe the bug

We have many issues (and work arounds) associated with CAD, the open ones I can find are:
 #1319 #1309 #1108 #1090 #1071 #1045 #902 #682 #513 

These seem to all relate to the Topological naming of elements in FreeCAD. This is a known issue for FreeCAD and is one of the main aims for the v0.21/v1 release cycle which is aiming to be released in 2023.

For some background reading the current progress in fixing this is detailed here:
https://github.com/realthunder/FreeCAD_assembly3/wiki/Topological-Naming

with the current FreeCAD branch:
https://github.com/FreeCAD/FreeCAD/compare/master...development/toponaming

Some background on the FreeCAD wiki and forum.
https://wiki.freecadweb.org/Topological_data_scripting
https://wiki.freecadweb.org/Topological_Naming_Project
https://wiki.freecadweb.org/Topological_naming_problem
https://forum.freecadweb.org/viewtopic.php?f=10&t=27278

The workarounds we have are understandably brittle after reading the above, and the option of just caching the shapes as @ivanmaione is working on in #1295 based off the ADR #1196 will hopefully alleviate some of the problems although not all.

It would be nice to keep our Matryoshka CAD structure or at least return to it at a later date once the above issues are (more) solved.

EDIT: The FreeCAD api looks like there will be some changes, the current release notes are here: https://wiki.freecadweb.org/Release_notes_1.0

Work towards this is progressing (they even have a gantt chartt!! https://github.com/FreeCAD/FreeCAD/issues/8432#issuecomment-1452745031)

**Comment by sebkahn** [comment]
Congrats on finding that !!

**Comment by je-cook** [comment]
Current tracking issue https://github.com/FreeCAD/FreeCAD/issues 8432

**Comment by luzpaz** [comment]
Just a heads up that Toponaming won't be fixed in FreeCAD v0.21.x  
Best place to track progress is https://github.com/orgs/FreeCAD/projects/2

**Comment by je-cook** [comment]
Thanks! Will definitely keep an eye on that project.
