### ISSUE TITLE
Inconsistent electrical current units

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#1389]
## Description

Whilst working on #1388, I noticed what looked like a unit conversion from MA to A when instantiating a `BetaIpProfile`, relevant code on develop [here](https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/75912fcab2ca0cb3d4fe3751bfe6aaccf87d95dd/examples/design/EU-DEMO/EUDEMO_builders/plasma.py#L286). Looking through our existing parameters in `Configuration`, the [non-zero electric current quantities](https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/develop/bluemira/base/config.py#L72) are in `MA` but [our conventions](https://bluemira.readthedocs.io/en/latest/conventions.html#unit-convention) say electric current should be in `A`. This is why we've got this case where a conversion is necessary; the function takes current in `A` (as it should), but the electrical current parameters are in `MA`.

We should resolve this by using either `A` or `MA` across the board.

**Comment by CoronelBuendia** [comment]
Yes, we should use `[A]` across the board as specified in the docs: https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/develop/documentation/source/conventions.rst
