### ISSUE TITLE
Implement unit management in new ParameterFrame

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#1421]
## Description of issue / requirement to address

The new `Parameter` class stores a unit string, but does not perform any sort of unit conversion/validation. We should add functionality to the `Parameter` class such that it can perform unit conversions on the fly.

## Proposed solution

The following should be considered/implemented:

- Use `pint` as a backend to validate that units strings are valid units.
- Make `unit` a compulsory constructor argument in `Parameter`.
- Convert the parameter value to a standard Bluemira unit in the constructor.
    - This actually might be better to do in `ParameterFrame`, as `Parameter` is a bit more general. So have a list of standard units in `ParameterFrame` and perform unit conversions before the frame's parameters are constructed.
- Add a `value_as_unit` method to retrieve values in a specific unit.
- Add `unit` argument to `set_value` method.
    - So we can set parameter values in non-standard units.

**Comment by je-cook** [comment]
Closed in #1504
