### ISSUE TITLE
Remove old builder/design classes

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#1428]
## Description of issue / requirement to address

Feature branch `feature/builder_reactor_redesign` contains new implementations for builders/designers. We need to remove the old `Builder`/`Design` classes along with their examples.

## Outputs

- Removal of `Builder` class and usages replaced with new `Builder` class
- Removal of `Design` class and usages replaced
- Removal of examples using `Builder`
- Removal of examples using `Design`

**Comment by je-cook** [comment]
closed by #1422
