### ISSUE TITLE
Resolve `TransportSolver` and `Solver` inheritance vs. composition.

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#1448]
## Description of issue / requirement to address
At the moment in the fixed boundary equilibrium solver we have a `TransportSolver` class that uses a `Solver` in composition.

## Proposed solution

Consider using inheritance.

## Alternative solutions

Leave things as is.

## Additional context

As there are changes underway in the `Solver` coming, we've felt it best to wait for these changes to crystallise before considering a refactor, potentially using inheritance instead of composition. (I.e. split out issue from #1067 )

**Comment by je-cook** [comment]
Closed with #1506
