### ISSUE TITLE
Extract `Builder` from fixed boundary equilibrium module

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#1454]
## Description of issue / requirement to address

At present, using the soon to be updated approach to `Builder`s, the fixed boundary equilibrium solver interface requires a `Builder` input with a set of params, currently handled by a `Configuration` object.

This will change with the update to the base architecture, and we should try and find a way to make the equilibrium module more independent of the base architecture, in line with our modular strategy.

## Proposed solution

Refactor out `Builder` from the fixed boundary equilibrium solver. This may also need to be done for `Parameter`s and `Configuration`.

## Alternative solutions

Subject to debate..! This one is likely to be a little tricky.

## Additional context

The architecture refactor should make this cleaner and easier than it is at present, and it is not worth doing this in the initial fixed boundary equilibrium PR.

**Comment by je-cook** [comment]
closed in #1506
