### ISSUE TITLE
decorated ParameterFrame != dataclass style ParameterFrame

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#1539]
## Describe the bug

See title (#1523 for context)

## Steps to reproduce

Steps to reproduce the behaviour:

```python
@dataclass
class MyParameterFrame(ParameterFrame):
    """A ParameterFrame"""

    A: Parameter[float]


# this works the same
@parameter_frame
class MyDecoratedFrame:
    """A ParameterFrame made with a decorator"""

    A: Parameter[float]

mypf = MyParameterFrame.from_dict({"A": {"value": 5, "unit": ""}})
mypf2 = MyParameterFrame.from_dict({"A": {"value": 5, "unit": ""}})
mydecpf = MyDecoratedFrame.from_dict({"A": {"value": 5, "unit": ""}})

mypf == mypf2  # True
mypf == pydecpf  # False

```

## Expected behaviour

Both should be true

## Screenshots / Tracebacks

If applicable, add screenshots / tracebacks to help explain your problem.

## Environment (please complete the following information)

- OS: [e.g. Ubuntu 18.04]
- Version [e.g. 0.0.x]
- Branch (if developing) [e.g. develop]

**Comment by hsaunders1904** [comment]
Closing this, as the decorated `ParameterFrame` has been removed #1607
