### ISSUE TITLE
Resolve some sonarcloud code smells introduced in feature branch

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#1541]
## Description

The PR for merging the feature branch into develop (#1536) had quite a few code smell warnings from sonarcloud. Some of these are not issues (e.g., 'name does not match regex' for tests, and or, parmeter names), but there are several that are worth looking into.

Here's the sonarcloud report (please don't expire 🙏 - I can't work out if you can export the report somehow)
https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&sinceLeakPeriod=true&pullRequest=1536&id=Fusion-Power-Plant-Framework_bluemira

**Comment by je-cook** [comment]
We are at least on a downward trend https://sonarcloud.io/project/activity?id=Fusion-Power-Plant-Framework_bluemira&graph=issues
