### ISSUE TITLE
Update PROCESS radial build

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#158]
In GitLab by @sebkahn on Mar 5, 2021, 24:29

## Description

After a review of the `rebuild_RB_dict` function on `PROCESSwrapper` module several inconsistent features with regards to latest PROCESS developpements has been spotted.

1. There is no need to make a distinction on resistive coil and SC coil mid-plane radial build anymore. The tapering info must be present somewhere though ... The main different is probably the absence of insertion gap for ST, but it can still remain having a thickness of 0 (if it is not causing any numerical issues @DanShort12, @CoronelBuendia).
2. Not sure if the order of the `rb = self.params["Radial Build"]` is build defines the radial build order. If it is the case, the radial build exatracted from PROCESS runs is wrong. Even if it is not the case, it makes more sense to write it in the good order in the code.
3. The Winding pack insertion gap and the WP ground insulation thickness are now included in the WP radial thickness, allowing a simplification of the build. The question is probably, do we really want to detail the ground insulation thickness or 
4. The spherical case radial build in the ST seems to be frozen to some quite random values, should these values be taken from the PROCESS input file instead ?
6. The radial build is now taken consistently on the middle of the TF coil.
7. The TF tapering factor is not included in the variable fetched in PROCESS.
8. The TF coil build is shown outside the radial build, this is confusion an impossible to catch for non expert. The TF thickness should be replaced by 

## Tout doux list (read to do list but in a very soft and relaxed way)

* [ ] Supress the if statement for ST. Check if having a 0 value on insertion gap is causing any numerical issues if yes, suppress the `tfinsgap` layer in the radial build though. If done consistently, this will do all the job.
* [ ] Correct the order the parameters are added in `rb` to avoid confusing the reader (the PROCESS variable names are already enough of a pain).
* [ ] Modify the PROCESS radial build to include the TF one.

Ref: @DanShort12, @CoronelBuendia and @shaildesai96 

Best regards     
Seb

**Comment by CoronelBuendia** [comment]
This, if handled at all, would be handled in the STEP reactor scripts
