### ISSUE TITLE
TF coil toroidal thickness

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#160]
In GitLab by @DanShort12 on Mar 8, 2021, 14:41

## Description

Increasing the TF coil toroidal thickness reduces the resistive heat dissipation. This can be integrated into BLUEPRINT as TF coil optimization procedure once the poloidal plane PF placement optimization is performed. 

However this needs to include some thickness limits probably driven by remote maintenance issues or access for heating/pellets and divertor pumping, that may not be trivial to capture. Some stress and structural constraint may be also present. Eventual coil joints may also play a role.

## Proposal

* [ ] Evaluate the minimal space between TF coil legs from access needs prescription in a manner that can vary in size and aspect ratio.
* [ ] Define the toroidal thickness Keep out zone.
* [ ] Correct the TF shape and resistive losses provided by PROCESS.

Best regards      
Sebastien Kahn

Ref: @sebkahn

**Comment by CoronelBuendia** [comment]
I think this is a STEP builder specific issue, closing as I reckon it should live in a separate repo.
