### ISSUE TITLE
Documentation page title wrong version on readthedocs

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#1604]
## Describe the bug

The page header title has the wrong version in it on readthedocs. Probably because of how checkout of the repo happens

## Steps to reproduce

Navigate to rtd
find `Welcome to bluemira documentation - bluemira <version> documentation` in the html header.
`<version>` is wrong

## Screenshots / Tracebacks

If applicable, add screenshots / tracebacks to help explain your problem.

## Environment (please complete the following information)

- OS: [e.g. Ubuntu 18.04]
- Version [e.g. 0.0.x]
- Branch (if developing) [e.g. develop]

**Comment by CoronelBuendia** [comment]
I don't see this... 
![image](https://user-images.githubusercontent.com/26097289/204828213-5ecb6a3b-fe47-40d5-8d32-31c48fa2fd7e.png)
still an issue?

**Comment by je-cook** [comment]
yep 

![image](https://user-images.githubusercontent.com/81617086/204832250-57a5b058-ae49-454e-829d-9c5c076bf7d9.png)
