### ISSUE TITLE
Rename RunMode enum in solver module

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#1608]
## Description of issue / requirement to address

The naming of the `RunMode` enum in `bluemira.base.solver` is causing a few annoyances. Generally, when defining a Solver for an external code, we scope everything under the code's namespace; we use `process.Solver` and `process.RunMode`.

The annoyance is that we then have to alias `bluemira.base.solver.RunMode` to something else, so we don't get a name-clash when we define the `RunMode`s for the external code's Solver. We end up doing something like `from bluemira.base.solver import RunMode as RunModeBase`.

## Proposed solution

Rename `RunMode` -> `RunModeBase`.

## Alternative solutions

We could rename the run modes of the concrete solvers, so, for example, we'd have `plasmod.PlasmodRunMode.RUN` instead of `plasmod.RunMode.RUN`.

**Comment by je-cook** [comment]
fixed in #2517
