### ISSUE TITLE
BLUEPRINT Parameter declaration

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#161]
In GitLab by @sebkahn on Mar 14, 2021, 24:41

## Description

Parameters can and are added/defined in different sections of the code. This way it is easy to
- Define two variables for the same quantity

And it is hard to:
- Interface back BLUEPRINT with PROCESS
- Have a global overview of the parameters
- Automatically document the BLUEPRINT variables

Is it possible to make all the BLUEPRINT parameters in one place and keep it there ? 
Is it possible to make sure the parameter frame is not updated in different sections of the code ?

Best regards    
Seb

**Comment by je-cook** [comment]
This done from the bluemira side and as of #1431 being closed soon we can generate the parameterframes. The duplication of parameters is an issue for each reactor designer
