### ISSUE TITLE
tinstf not passed to PROCESS

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#164]
In GitLab by @DanShort12 on Mar 18, 2021, 16:49

For the EU-DEMO case the PROCESS value `tinstf` (BLUEPRINT value `tk_tf_ins`)is not passed to PROCESS. This means the value used by PROCESS is not the same as BLUEPRINT (the PROCESS default value is 0.013, while the BLUEPRINT value is 0.08). @CoronelBuendia - is that intentional or should this be added to the mapping for values that BLUEPRINT write to PROCESS?

**Comment by sebkahn** [comment]
Hello 

@DanShort12 and @CoronelBuendia is this issue still needs update from me?

**Comment by je-cook** [comment]
PROCESS issue still in progress but on radar

**Comment by geograham** [comment]
Value for 'tinstf' is now passed to PROCESS for EUDEMO radial build (N.B. typo above, value is set to 0.008 m). Associated issue regarding 'tfinsgap' has been discussed and closed in papercuts (Asymmetric DEMO insertion gap #1288).
