### ISSUE TITLE
Fixed boundary equilibrium solver not converging.

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#1675]
## Describe the bug

Run the fem fixed boundary equilibrium example and note that the G-S solver always reaches max iterations (30).

This did not use to be the case; it used to converge in 9 or 10 iterations every time.

From a brief look, it looks like the various PRs I had put in to improve the fixed boundary solver were not rebased before being merged when I was off. Unsure exactly, but the fact is code is missing that should be there.

E.g. https://github.com/Fusion-Power-Plant-Framework/bluemira/pull/1461/files followed by https://github.com/Fusion-Power-Plant-Framework/bluemira/pull/1464/files

## Environment (please complete the following information)

- OS: 
- Version: 
- Branch:

**Comment by je-cook** [comment]
Oops, can reproduce locally. I did rebase them but there were a few quality updates needed to bring it into line with everything else
