### ISSUE TITLE
Fixed boundary equilibrium plotting is "all or nothing"

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#1683]
## Description of issue / requirement to address

When running a fixed boundary equilibrium solve, there is a fair amount of text displayed, and no plots are shown in `plot=False` is passed in.

If `plot=True` is passed in, there are a huge number of plots that come up at each outer and inner iteration. These plots must be closed for the solution to continue. The plots are not saved.

This comes from a time during development when all these plots were useful for debugging, but as for the purposes of "plotting to display" I'd argue it's overkill, and quite fiddly (closing all the windows every time they pop up).

We have many `plot` flags in various parts of the code, and they tend to provide a relatively concise (opinionated) view of the problem. In the free boundary equilibrium solve, a single plot is updated at each iteration, and does not stop the rest of the code from running.

## Proposed solution

Plotting features we want in the transport/fixed boundary equilibrium solve:
* concise plotting for display purposes (minimal number of figures) (using `plot=True` as in the rest of bluemira)
* detailed plots for debugging purposes which are saved
* the ability to create GIFs 
* the same colour schemes as for the free boundary equilibrium (e.g. Jtor, psi, field, etc. all have a specific colour map in equilibrium/plotting.py)
```python
PLOT_DEFAULTS = {
    "psi": {
        "nlevels": 15,
        "cmap": "viridis",
    },
    "field": {
        "nlevels": 15,
        "cmap": "magma",
    },
    "current": {
        "nlevels": 30,
        "cmap": "plasma",
    },
...
```

## Additional context

@ivanmaione

**Comment by ivanmaione** [comment]
I am fine with the proposed approach, i.e. to reduce the number of plotting pop-ups in favor of auto-updating plotting and stored images for debugging purposes. However, it would be great if we could, in some way, extend the functions of the plotting class and make some classes (as that related to plasmod solver and the fem magnetostatic) "Plottable".

**Comment by je-cook** [comment]
I'm happy with the approach but are we going to have time to get this into version 1?

**Comment by ivanmaione** [comment]
I don't think we would have the time if we want to implement something more "general" as in my mind, but maybe @CoronelBuendia can just modify the part in the fem_fixed_boundary to get the same behavior of the free_boundary. In case, I would be fine with that for the moment.
Just as a note: with the proposed approach, PyCharm users must disable the SciView functionality (that redirects plots), but considering the low number of PyCharm users at the moment (probably just 1 :P), I think it is not a big deal.
