### ISSUE TITLE
Run a PROCESS without template

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#170]
In GitLab by @sebkahn on Mar 30, 2021, 16:55

## Description 

It can be usefull to run *PROCESS* only using a given input file without using any template.

## Proposal 

Add a "run input" process_mode that
 - Run PROCESS without modifying the considered template IN.DAT
 - Load PROCESS ouptuts ("read all")

branch: https://gitlab.com/CoronelBuendia/BLUEPRINT/-/tree/issue-343-run-PROCESS-without-template (ready for review)    
Merge request: https://gitlab.com/CoronelBuendia/BLUEPRINT/-/merge_requests/300 (ready for review) 

Best regards      
Seb

**Comment by je-cook** [comment]
this is done as far as I'm aware
