### ISSUE TITLE
Core plasma e.m. radiation heat on FW

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#171]
In GitLab by @sebkahn on Apr 6, 2021 15:43

# Core plasma e.m. radiation heat on FW

## Description
Core &gamma; radiation are bound to be a major source of heat in a tokamak first wall. Photons from the core arises from three mains phenomena:

1. Line radiation: Ions still carying electrons despite plasma temperature will emits photons when exited electrons get to lower energy orbits. This type of radiation mainly concerns high Z imprities and is documented in the following PROCESS and SYCOMORE papers [1-2]
2. Bremstrahlung: Rotating charged particles emits photons and must be integrated, becoming a important source of radiation [1-2]
3. Sycrotron: Additionnal radiation source I need to inderstand [3-4]
Radiation effect is planned to be dealt using Cherab [5] itself using RaySec [6] from a defined 2-3D source location.

## Plan

- [ ] Install Cherab
- [ ] Install RaySec (not mendatory be potentially usefull for future work)
- [ ] Parametrize a 2D source using the plasma magnetic closed surfaces
- [ ] Write a function calculating the heat flux generated by this source on the FW
- [ ] Work on a reduced model providing the radiation source term from plasma and impurity profiles (hard)

Best regards
Seb

Ref: @mkovari, @DanShort12, @CoronelBuendia, @DarioV86 and @byc-chan

[1] H. Lux, R. Kemp, D.J. Ward, M. Sertoli Fusion Engineering and Design 101 (2015) 42-51
[2] Johner Jean (2011), Fusion Science and Technology, 59:2, 308-349, DOI: 10.13182/FST11-A11650
[3] Albajar, Nuclear Fusion 41 (2001) 665
[4] Fidone, Giruzzi, Granata, Nuclear Fusion 41 (2001) 1755
[5] https://github.com/cherab
[6] https://github.com/raysect

**Comment by je-cook** [comment]
closed by #2224
