### ISSUE TITLE
Convert OptVariables to a dataclass

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#1739]
## Description of issue / requirement to address

OptVariables is currently hidden within geometry parameterisations as eluded to in #608. Its not very accessible to the user by making it hard to see what variables are available.

## Proposed solution

Convert OptVariables to a dataclass like we do for ParameterFrame. Each OptVariable subclass can then contain the variables for a given parameterisation 

## Alternative solutions

leave as is 

## Additional context

Diving into parameterisations for #1287 found it hard to pull out information

**Comment by hsaunders1904** [comment]
`OptVariable`s and `BoundedVariable`s are pretty much only used in `GeometryParameterisation`s, so we should really think about how we can make it easy for users (and us) to implement a `GeometryParameterisation`.

My comments are more to do with geometry parameterisations, but they are linked, and maybe updates to `OptVariable` can help make the geometry parameterisation interface more intuitive.

- As alluded to in #608, it's difficult to work out what `var_dict` is actually doing. It would be good if we could standardize (and document) how we intend people to initialise these parametrisations.
- Users are currently required to call the super class constructor in their derived classes. This is probably fine (although I'd consider it a bit of an antipattern, see [here](https://en.wikipedia.org/wiki/Call_super) and [here](http://journal.stuffwithstuff.com/2012/12/19/the-impoliteness-of-overriding-methods/)), but we should document that they must do it. The base class constructor is only initialising some variables, so we could consider making these [abstract]properties.
