### ISSUE TITLE
Proposal: Add a run mode to bypass PROCESS

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#175]
In GitLab by @DanShort12 on Apr 12, 2021, 17:47

Currently, if a user does not have PROCESS installed locally then their only way to generate a run is to use the mock PROCESS functionality. However, that mode of running can require a user to update parameters both in their mock PROCESS json file and in their BLUEPRINT run configuration, which can lead to not obvious discrepancies. We should consider being able to run BLUEPRINT in a mode that bypasses the systems code functionality altogether if e.g. the `process_mode` key is not provided, or is set to None. That would allow the run to be controlled just from the BLUEPRINT parameters.

**Comment by je-cook** [comment]
The read and readall modes covers this use case I think, I dont think defaulting to a read mode will improve the situation I think defaulting to run is more obvious
