### ISSUE TITLE
Proposal: Remove OpenMOC dependency (and code)

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#178]
In GitLab by @DanShort12 on Apr 21, 2021, 15:52

Using OpenMOC in BLUEPRINT creates a dependency that adds additional maintenance and potential installation overhead. As OpenMOC is not used due to the analysis performed in earlier phases, which identified that the anisotropic cross sections required for fusion neutronics were not supported in OpenMOC, we should consider removing it along with the code to interface with it.

**Comment by CoronelBuendia** [comment]
OpenMOC is not a dependency of BLUEMIRA at present, this dates back to the BLUEPRINT repository. No decision taken here as to whether or not interface to OpenMOC in future
