### ISSUE TITLE
Resistive TF Coils class

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#179]
In GitLab by @DanShort12 on Apr 22, 2021, 16:26

Currently there is a lot of complexity in the `ToroidalFieldCoils` class, which is being driven by the tapered pictureframe (TP) parameterisation. We should make a `ResistiveTFCoils` class to ameliorate (good word!) that complexity.

**Comment by sebkahn** [comment]
Hello 

As @CoronelBuendia pointed out, the resistive tapering is not exactly something related to the choice of conductor, but rather a specific casing / WP shape that can be (only) used by resistive coils.

On the other hand, resistive coils can use conventionnal winding pack geometries.

So I gather, the resistive option is rather a case/WP specific structure for the central collumn.

Please see @shaildesai96 PR that should at least partly address that notion:
https://github.com/Fusion-Power-Plant-Framework/bluemira/pull/519

**Comment by CoronelBuendia** [comment]
I think this is a STEP builder specific issue, closing as I reckon it should live in a separate repo.
