### ISSUE TITLE
Feature: arbitrary cross section current sources

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#1816]
## Description of issue / requirement to address

Currently we only have analytical forms of rectangular cross section magnets following an arbitrary path. 

It would be nice to be able to support analytical forms of other cross sections.

## Proposed solution

This paper even though it is for permanent magnets may help with the generalisation:
doi.org/10.1016/j.jmmm.2020.166894

EDIT (Matti): I have found a tractable formulation of a volumetric integral approach for vector potential and magnetic field here: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=4407584. Of the dozen or so approaches I ended up looking at, this was by far the most understandable and easy to implement. I have written a PR for this, but a lot remains to be done for me to  be happy with this:

* [ ] Fix tests
  * [ ] Babic and Aykel verification test from the `TrapezoidalPrism` is failing and I don't know who is right, but I suspect we have some singularity issues
  * [ ] Benchmarking with the `TrapezoidalPrism` we see differences when `alpha` and `beta` are not equal. Again not sure who is right.
* [ ] Add tests:
  * [ ] Test that two triangle sources make up a rectangular source
  * [ ] Test continuity of subsequent sources
  * [ ] Test field and potential symmetry of a symmetric polyhedral current source
  * [ ] Verification test of field and potential from a circular rectangular cross-section make with a polyhedral circuit with analytical cylindrical equivalents
  * [ ] Test rotations 
  * [ ] etc..
* [ ] Make some assembly utilities (see e.g. #2704)
* [ ] Write documentation
* [ ] Improve performance (e.g. finish JITting)
* [ ] Add examples:
  * [ ] Add a simple `PolyhedralPrismCurrentSource` example
  * [ ] Add a simple `AbitraryPlanarPolyhedralCircuit` example
* [ ] etc..

@kj5248 
## Alternative solutions

It is possible to just use an arrangement of `BiotSavartFilament`s to have a very similar result.

## Additional context

This is useful for STEP, in that arbitrary cross-section conductors can be used, but I was interested in this stuff because I needed a general way to do volume integrals to calculate things like vector potential, and then self-inductance, etc. It's also potentially useful for stellarators, in that the conductors no longer need to be planar.

**Comment by CoronelBuendia** [comment]
I looked at this a while back: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=123865
I was scared by the lack of mention of singularities and how to treat them, but it's possible this could work, perhaps also including this stuff, which I had failed to note last time: https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=101115
