### ISSUE TITLE
Add examples to documentation build

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#1825]
## Description of issue / requirement to address

Add Jupyter notebook examples to documentation.

Following #1784, we no longer keep a copy of the rendered Jupyter Notebook examples in the repo. We should make sure that rendered versions of the notebooks are available online. We can do this by building them into our RTD documentation.

**Comment by je-cook** [comment]
Looking at nbsphinx which seems to cover our usecase it is what readthedocs suggests https://docs.readthedocs.io/en/stable/guides/jupyter.html
