### ISSUE TITLE
Add mock CLI jupyter notebook to examples/cli

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#185]
In GitLab by @lukethehuman on May 10, 2021, 12:26

While the Command Line Interface is currently documented, there is no interactive notebook in the examples folder. We could add such a notebook.

It would work best with mocked inputs/outputs and a mocked reactor build to allow quick testing of whether CLI inputs are valid and printing what the CLI would do for the given inputs.

In discussion, @je-cook suggested this might be possible using the following structure:
```python
import sys
sysold = sys.argv
# modify sys.argv
# run cli stuff
# modify sys.argv
sys.argv = sysold
```

**Comment by je-cook** [comment]
CLI doesnt exist anymore, if and when it is recreated it will be rearchitected
