### ISSUE TITLE
Automatic labelling of issues for preliminary triage

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#1855]
## Description of issue / requirement to address
With the onset of new users, the number of issues is expected to increase. Issue triage will become important.

## Proposed solution
GitHub allows for automatic labelling using Action bots. This could be implemented for new issues that haven't been assessed by the developers yet (_e.g._ "**awaiting-triage**" and/or "**user-issue**" labels).

Additionally, other situations could also be automatically labelled (_vide_ screenshots for examples), such as:
- adding "**awaiting-user-feedback**", after a developer answers;
- removing "**awaiting-user-feedback**" and/or adding "**awaiting-developer-feedback**", after a non-developer answers;
- adding "**issue-in-module-X**",  if specific modules are mentioned in issue;
- ...

![post-developer-reply](https://user-images.githubusercontent.com/40567154/212889431-5eff5e66-e488-48fd-816b-4f26b898ca02.png)
![post-user-reply](https://user-images.githubusercontent.com/40567154/212889543-8b7c8047-6ed1-4713-bc87-fdb37c4a9206.png)

## Alternative solutions
Hire someone to perform manual issue triage. :stuck_out_tongue:

**Comment by je-cook** [comment]
I dont think this is necessary with our current volume of interactions, maybe in future if someone want to write it.
