### ISSUE TITLE
TF coil weight

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#186]
In GitLab by @sebkahn on May 10, 2021, 15:17

## Description

The TF coil weight info is usefull for remote maintenance perspectives. It may be good to calculated in BLUEPRINT:

1. Calculate the TF coil volume
2. Calculated the weight assuming relevant material densities

**Comment by CoronelBuendia** [comment]
This is STEP-specific and fairly trivial. In future we would like to assign materials to volumes directly, but perhaps warrants a separate, more generic issue.
