### ISSUE TITLE
Cannot deepcopy PictureFrame

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#1893]
## Describe the bug

It is not possible to `deepcopy` a `PictureFrame`. It causes a `ValueError`.

## Steps to reproduce

```python
from copy import deepcopy

from bluemira.geometry.parameterisations import PictureFrame

p = PictureFrame()
p2 = deepcopy(p)
```

## Expected behaviour

The copy should succeed.

## Screenshots / Tracebacks

<details>

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    ----> 1 p2 = deepcopy(p)

    File ~/mambaforge/envs/bluemira/lib/python3.8/copy.py:172, in deepcopy(x, memo, _nil)
        170                 y = x
        171             else:
    --> 172                 y = _reconstruct(x, memo, *rv)
        174 # If is its own copy, don't memoize.
        175 if y is not x:

    File ~/mambaforge/envs/bluemira/lib/python3.8/copy.py:270, in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
        268 if state is not None:
        269     if deep:
    --> 270         state = deepcopy(state, memo)
        271     if hasattr(y, '__setstate__'):
        272         y.__setstate__(state)

    File ~/mambaforge/envs/bluemira/lib/python3.8/copy.py:146, in deepcopy(x, memo, _nil)
        144 copier = _deepcopy_dispatch.get(cls)
        145 if copier is not None:
    --> 146     y = copier(x, memo)
        147 else:
        148     if issubclass(cls, type):

    File ~/mambaforge/envs/bluemira/lib/python3.8/copy.py:210, in _deepcopy_tuple(x, memo, deepcopy)
        209 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
    --> 210     y = [deepcopy(a, memo) for a in x]
        211     # We're not going to put the tuple in the memo, but it's still important we
        212     # check for it, in case the tuple contains recursive mutable structures.
        213     try:

    File ~/mambaforge/envs/bluemira/lib/python3.8/copy.py:210, in <listcomp>(.0)
        209 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
    --> 210     y = [deepcopy(a, memo) for a in x]
        211     # We're not going to put the tuple in the memo, but it's still important we
        212     # check for it, in case the tuple contains recursive mutable structures.
        213     try:

    File ~/mambaforge/envs/bluemira/lib/python3.8/copy.py:146, in deepcopy(x, memo, _nil)
        144 copier = _deepcopy_dispatch.get(cls)
        145 if copier is not None:
    --> 146     y = copier(x, memo)
        147 else:
        148     if issubclass(cls, type):

    File ~/mambaforge/envs/bluemira/lib/python3.8/copy.py:230, in _deepcopy_dict(x, memo, deepcopy)
        228 memo[id(x)] = y
        229 for key, value in x.items():
    --> 230     y[deepcopy(key, memo)] = deepcopy(value, memo)
        231 return y

    File ~/mambaforge/envs/bluemira/lib/python3.8/copy.py:172, in deepcopy(x, memo, _nil)
        170                 y = x
        171             else:
    --> 172                 y = _reconstruct(x, memo, *rv)
        174 # If is its own copy, don't memoize.
        175 if y is not x:

    File ~/mambaforge/envs/bluemira/lib/python3.8/copy.py:264, in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
        262 if deep and args:
        263     args = (deepcopy(arg, memo) for arg in args)
    --> 264 y = func(*args)
        265 if deep:
        266     memo[id(x)] = y

    File ~/mambaforge/envs/bluemira/lib/python3.8/enum.py:339, in EnumMeta.__call__(cls, value, names, module, qualname, type, start)
        314 """
        315 Either returns an existing member, or creates a new enum class.
        316
    (...)
        336 `type`, if set, will be mixed in as the first base class.
        337 """
        338 if names is None:  # simple value lookup
    --> 339     return cls.__new__(cls, value)
        340 # otherwise, functional API: we're creating a new Enum type
        341 return cls._create_(
        342         value,
        343         names,
    (...)
        347         start=start,
        348         )

    File ~/mambaforge/envs/bluemira/lib/python3.8/enum.py:663, in Enum.__new__(cls, value)
        661 ve_exc = ValueError("%r is not a valid %s" % (value, cls.__name__))
        662 if result is None and exc is None:
    --> 663     raise ve_exc
        664 elif exc is None:
        665     exc = TypeError(
        666             'error in %s._missing_: returned %r instead of None or a valid member'
        667             % (cls.__name__, result)
        668             )

    ValueError: functools.partial(<function PictureFrameTools._make_flat_leg at 0x7f18c1a38310>) is not a valid PFrameSection

</details>

## Environment (please complete the following information)

- Branch: develop

**Comment by je-cook** [comment]
Possible after #2396 merge
