### ISSUE TITLE
Thread in semianalytic psi for use in Coil

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#191]
In GitLab by @CoronelBuendia on May 18, 2021, 09:43

Now that we have accurate psi resolution inside rectangular cross-section PF coils, need to thread this into Coil via `control_psi` etc.

This will change the amount of O and X points that are found inside the coils when solving equilibria, which has the potential to change the results from equilibria.

**Comment by je-cook** [comment]
@CoronelBuendia is this now covered or should it be part of the coils refactor?

**Comment by je-cook** [comment]
with the new structure in #708 it would be reasonably straightforward to integrate this once written into `_field.py`
