### ISSUE TITLE
Create a generic Workflow definition for running complex systems

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#196]
In GitLab by @je-cook on May 27, 2021, 10:07

As mentioned in #420 a generic workflow for each external code should be a setup-run-teardown approach. This also is a collection of thoughts after a discussion with @DanShort12.

For complex systems that could depend on some external and some internal methods a [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph) could be set up that can be internal in bluemira and methods would be called based on what is defined for the run.

To achieve this we will need:

- A full list and dependency tree (essentially a DAG) of the current functions and methods with a minimal list that could be eg `make_equilibrium` etc similar to what is in `reactor.build` at the moment but flexibly defined.
- A generic in-run-out skeleton that will be inherited from for each new code adding for instance run and mock classes for process. Run then itself could be a complex set of nodes in the DAG.
   - in  would define any intrinsic things for input to codes
   - run would run a given instruction set eg create 'x' or run code 'y'
   - out would do some (probably extra) error checking on the output

All of this would facilite the use of bluemira for exploring a given parameter space.

**Comment by CoronelBuendia** [comment]
@je-cook this could do with a wee update / close, perhaps?

**Comment by je-cook** [comment]
I'm pretty sure this all done now. Especially with how we use build config.
