### ISSUE TITLE
Change names in licence to Bluemira Developers

### ISSUE THREAD

**Issue by oliverfunk** [Fusion-Power-Plant-Framework/bluemira#1990]
## Description of issue / requirement to address

The names in the copyright licence at the top of each file will need to keep growing as more people contribute to the development of Bluemira and may not accurately attribute all those who've worked on the project.

This isn't scalable. It would be better to attribute all "Bluemira Developers" where their names etc. are in the CITATION.cff file.
This also gives an easy way for any work that needs to cite Bluemira in an academic paper to do so.

We will also register Bluemira on [Zenodo](https://zenodo.org/) which provides an even easier way to cite Bluemira.

## Proposed solution

Replace the names of each contributor with "Bluemira Developers" at the top of each file.

**Comment by je-cook** [comment]
Great, all sounds good to me @tplobo fyi you can add the new copyright to your stuff once this issue is closed
