### ISSUE TITLE
PROCESS obsolete variables are not mapped back properly

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#2012]
## Describe the bug

When a variable is obsolete in PROCESS we change the input name to the new value in the setup task, separately on teardown we make sure we read in the variable names as the new name.

The mapping back to bluemira relys on the old variable name meaning that its output value is set to None because it will not be found in the output as we have converted it to the new name. I think this will only effect OUT variables as IO and INPUT will be converted to the new names and written.

@CoronelBuendia @ajpearcey

## Steps to reproduce

See the commit before #2011 and run eudemo `thkcas` is obsolete and set to None 

## Expected behaviour

The value gets set and mapped back to bluemira

## Environment (please complete the following information)

- OS: 
- Version: 
- Branch:  22658df7dff4afdff639d02aa8bd76b2cfee9360

## Additional context

#2011

**Comment by CoronelBuendia** [comment]
@je-cook  is this still relevant in #2522 ?

**Comment by je-cook** [comment]
yes I think so, although as we have updated all the variable names it wont bite us for a while
