### ISSUE TITLE
Build issue hysteresis

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#203]
In GitLab by @makeclean on Jun 15, 2021, 14:37

Ubuntu 18.04 via Docker, it seems that the order of requirements.txt matters. I find a build failure, since MeshPy=2021.1 needs pybind11 to be installed first otherwise fails. However, the C++ bits work since the C++ binding are installed with apt-get, so its a weird failure. I resolved this by installing pybind11 first, then rerunning the install instruction.

**Comment by CoronelBuendia** [comment]
Unlikely this is still relevant, given all the changes we're gone through.. closing for now, happy to reopen if confirmed this is still a problem.
