### ISSUE TITLE
Free boundary equilibrium reformulation for divertor optimization

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#204]
In GitLab by @sebkahn on Jun 21, 2021, 12:02

## Description

The free boundary optimisation problem does not include divertor considerations at present.This should be made possible somehow.

## Proposal

The proposal is to make a configurable `OptimisationProblem` in which:
 - The objective function for an equilibrium [current &or position] optimisation can be set by the user
     - Minimisation of error to magnetic constraints
     - Minimisation of the absolute sum of coil currents
     - Minimisation of the total volume of coils 
     - Combined and weighted versions of the above and others, including e.g. connection length &or flux expansion
 - The constraint function(s) for an equilibrium [current &or position] optimisation can be set by the user
     - Error to magnetic constraints
     - Force, field, current constraints

## Additional context

As discussed with @alexanderianblair and @CoronelBuendia on the 3/11/2021

**Comment by CoronelBuendia** [comment]
@sebkahn @markj997 @alexanderianblair I believe that with #1027 all of the functionality required above will be possible, but not implemented "ready-made" as this will likely be quite a specific problem. Could we close this issue when that branch gets merged?
