### ISSUE TITLE
PF and TF coil casing needed for structural analysis

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#213]
In GitLab by @grc1v07 on Jul 9, 2021, 14:26

For STEP SPR designs in Batch 2 it will be required that each PF coil has a casing.  The casing should be co-centred with the PF coil, and be defined by a thickness parameter (the distance between the PF and case's outer surfaces).

**Comment by CoronelBuendia** [comment]
This is specific to STEP reactor implementation
