### ISSUE TITLE
Improve test coverage of firstwall reactor systems

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#215]
In GitLab by @helen-brooks on Jul 19, 2021, 15:01

There are a very large number of methods in systesm/firstwall.py which do not have a test. In part, this is a result of refactoring into smaller functions from MR !416, however this should also make it easier to test small chunks of functionality. Currently untested _directly_ (i.e. through direct invocation in a test) are:
- find_outer_point
- find_inner_point
- get_intersection_point
- FluxSurface.find_intersections
- FluxSurface.snip_flux_surface
- FluxSurface.find_first_intersection_dn
- FluxSurface.calculate_q_par_imp
- FluxSurface.calculate_q_par_local
- FluxSurface.calculate_q_par_local_hfs
- FluxSurface.calculate_incindent_angle
- FluxSurface.calculate_heat_flux_onto_fw_surface
- FirstWall.make_flux_contour_loops
- FirstWall.find_koz_flux_loop_ints
- FirstWall.find_strike_points_from_koz
- FirstWall.find_strike_points
- FirstWall.pick_flux_loops
- FirstWallSN.find_strike_points_from_params, FirstWallDN.find_strike_points_from_params
- FirstWallSN.make_2d_profile, FirstWallDN.make_2d_profile,
- FirstWallSN.make_flux_surfaces
- FirstWallSN.calculate_parameters_for_heat_flux
- FirstWallSN.calculate_heat_flux_lfs_hfs
- FirstWallDN.reshape_curve
- FirstWallDN.get_tangent_vector
- FirstWallDN.point_before
- FirstWallDN.make_outer_leg
- FirstWallDN.make_inner_leg
- FirstWallDN.find_intersections
- FirstWallDN.find_first_intersections
- FirstWallDN.calculate_parameters_for_heat_flux
- FirstWallDN.define_flux_surfaces_parameters_to_calculate_heat_flux
- FirstWallDN.calculate_heat_fluxes
- FirstWallDN.collect_intersection_coordinates_and_heat_flux
- FirstWallDN.calculate_heat_flux
- FirstWallDN.clipper
- FirstWallDN.modify_fw_profile

It may be that not every method above needs testing directly (e.g. indirectly may suffice), but coverage should probably be reviewed and improved.

Those tests which are implemented tend to only test some basic features e.g. existence of an attribute rather than compare equivalency of the output to some known values. They also don't in general test for changing input. Both points might be more easily addressed if more dummy input were used.

**Comment by CoronelBuendia** [comment]
Most of these functions no longer exist since the move to `ChargedParticleSolver` and the first wall tests seem to run forever, can we update the description of this or close the issue @helen-brooks @DarioV86 @sebkahn ?
