### ISSUE TITLE
Bounding box bug

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#2162]
## Describe the bug

While working on #2159 I was coming across a bug where the blanket I was building had a 'lip' at the bottom that wasn't being panelled. After some investigation, it turned out that, in the `design_ivc` function, when we create the 'cut wall boundary' wire (i.e., the wall boundary cut below the equilibrium's x-point, to make room for the divertor), the wire's bounding box was not consistent with the rest of the object. The bounding box's z-value was ~0.2 smaller than it should have been.

The cut wall boundary looks like this:
<img src=https://user-images.githubusercontent.com/33317174/234867831-994d400d-06a9-42a6-aa23-f29591915b38.png width=350>

The green line shows the z given by `cut_wall_boundary.start_point().z[0]` the red shows the z given by `cut_wall_boundary.bounding_box.z_min`.

See [34228d3](https://github.com/Fusion-Power-Plant-Framework/bluemira/pull/2159/commits/34228d30325b55078210690acd6b4529acf2da36) for more context.

## Steps to reproduce

I've tried to get an MRE, but I haven't managed to reproduce the bug 😞. Here are the steps to recreate the bug in the way that I found it.

1. Checkout [34228d3](https://github.com/Fusion-Power-Plant-Framework/bluemira/pull/2159/commits/34228d30325b55078210690acd6b4529acf2da36) in Git (`git checkout 34228d3`).
2. Add a break point to `eudemo/eudemo/ivc/__init__.py` line 76  in your IDE/debugger. 
3. Debug the EUDEMO reactor script.
4. To view the issue, run the following in the debug console:

	```pycon
	>>> cut_wall_boundary.bounding_box.z_min
	-5.701225441085458
	>>> cut_wall_boundary.start_point().z[0]
	-5.525853343944378
	>>> from bluemira.display import show_cad
	>>> show_cad([plasma_face, cut_wall_boundary], backend="POLYSCOPE")
	>>> cut_wall_boundary.bounding_box.z_min
	-5.525853343944378
	```

As you can see, when plotted, the shape corrects itself somehow. Honestly, this seems quite inconsistent, I'm still not 100% sure what's going on with it.

## Expected behaviour

The bounding box should be consistent with the start and end points of the wire.

## Environment (please complete the following information)

- OS:  Ubuntu 22.04 (WSL2)

**Comment by CoronelBuendia** [comment]
Here is an easier MWE, which is now in a test in #2166:

```python
import numpy as np
import pytest

from bluemira.geometry.bound_box import BoundingBox
from bluemira.geometry.face import BluemiraFace
from bluemira.geometry.parameterisations import PolySpline
from bluemira.geometry.tools import boolean_cut, make_polygon

ps = PolySpline(
    {
        "bottom": {"value": 0.509036},
        "flat": {"value": 1},
        "height": {"value": 10.1269},
        "lower": {"value": 0.2},
        "tilt": {"value": 19.6953},
        "top": {"value": 0.46719},
        "upper": {"value": 0.326209},
        "x1": {"value": 5},
        "x2": {"value": 11.8222},
        "z2": {"value": -0.170942},
    }
)

cut_box = BluemiraFace(
    make_polygon({"x": [0, 15, 15, 0], "z": [-7, -7, -5, -5], "y": 0}, closed=True)
)
wire = boolean_cut(ps.create_shape(), cut_box)[0]
print(wire.bounding_box.z_min)  # -5.078907714066715
```
