### ISSUE TITLE
Bug in boolean_2d_difference

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#223]
In GitLab by @helen-brooks on Aug 5, 2021, 09:54

Applying the `boolean_2d_difference` operation to subtract a square from the corner of an L-shape does not produce the expected result, namely two squares. Instead the result is shown in the second image. It appears to be the case that the underlying `PyClipper` opereration results in an open loop. In `PyClipperMixin.handle_solution` on line 173 in boolean.py we naively close this open loop, which is just the shortest path from (1,0) to (0,1), instead of going via the vertex at (1,1).

![L-shape](/uploads/a08ba8b0e8b04f71329749b399d2324e/L-shape.png)
![LminusSquare](/uploads/cf50aaa64fcee58324428e7118eaad8e/LminusSquare.png)

Here is a short script to reproduce this issue.
[l-shape.py](/uploads/605f739b7f31214e547fb7f742e703d2/l-shape.py)

**Comment by CoronelBuendia** [comment]
We no longer use pyclipper for 2-D boolean operations
