### ISSUE TITLE
Toroidal segmentation of banana and immersion blankets

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#224]
In GitLab by @helen-brooks on Aug 6, 2021, 11:47

The toroidal segmentation in the CAD may not necessarily be in units of n_TF, so will require some thought. Perhaps we can still do something periodic in 2PI/n_TF segments.

**Comment by CoronelBuendia** [comment]
This should be addressed on the STEP side
