### ISSUE TITLE
robust tests that use stdout/logging calls

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#227]
In GitLab by @je-cook on Aug 20, 2021, 13:37

For the next iteration of logging we need to make sure tests set their own logging level or we may get back into a state where tests fail for seemingly no reason. For instance `test_model.py::test_illconditioned` which lead to a deep hole before the reasoning was found in !415

**Comment by CoronelBuendia** [comment]
@je-cook this feels closed now.. am I wrong?

**Comment by je-cook** [comment]
I think we've avoided it but have never actually tackled it eg with Dan's suggestion. We just don't set the logging level in any of our tests (as far as I'm aware). It is probably still something we should do but no rush on it.

I don't think any of our tests check that with a certain log level the right message is returned

**Comment by je-cook** [comment]
This can be achieved on a per test basis with the pytest built in `caplog` fixture
