### ISSUE TITLE
Find a way to recover the configurability / selectability of optimisation problems as per the old interface

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#2332]

**Comment by je-cook** [comment]
This currently still works but the removal of MinimiseLengthGOP will mean there needs to be some code changes when we remove the old API.

Right now however everything is fine

**Comment by oliverfunk** [comment]
The new interface would not permit such a dynamic configuration of the GOP anymore, which I strongly believe is for the best. Allowing the Python class to be set dynamically from a config variable was not a good construct to begin with.

It obscures the code, makes it difficult to read and can be abused.

A better approach would be to implement the allowed objective functions into the designer (at the moment there's only one, the length of the `GeometryParameterisation`) and be set by checking a config variable, such "opt_problem".

This makes it clear to anyone reading the designer's code which GOP can be run and how it's setup.
