### ISSUE TITLE
3D Plotting will break in next couple of MPL upgrades

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#234]
In GitLab by @je-cook on Sep 3, 2021, 09:00

Our 3D plotting does some fancy things under the hood of mpl, I was trying to upgrade to 3.4.3 but it seems like there is more to it (see !448 for some details).

Both the `Plot3D` and `BPPathPatch3D` classes are affected in plottools.py

**Comment by CoronelBuendia** [comment]
@je-cook can we close this now?

**Comment by je-cook** [comment]
yeah
