### ISSUE TITLE
Remove unused module-level variable in equilibrium.py

### ISSUE THREAD

**Issue by bielsnohr** [Fusion-Power-Plant-Framework/bluemira#2343]
The `EQ_FOLDER` variable in `bluemira/equilibria/equilibrium.py` is unused anywhere else in bluemira. See line here:

https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/d283896ef405e235aa30f86712f1b3bc88db670f/bluemira/equilibria/equilibrium.py#L71

In my particular case of trying to use bluemira within a Docker container, the definition of this variable is problematic because the `data` folder (to which this path is supposed to point) is not currently copied over due to the `.dockerignore` file. A temporary fix is to simply create that folder, but longer term this should be removed because this variable has no function within the module.

I presume this variable would also cause a problem in your own Docker builds? If not, I am curious how you might circumvent this in a different way.

**Comment by bielsnohr** [comment]
Ah, just had a thought: I suspect when you are using your version of the Docker container in CI, the bluemira repo will be cloned into that container, and therefore the `data/` folder will be present in the expected place.

**Comment by bielsnohr** [comment]
Also, happy to submit a PR for this given how trivial it should be.

**Comment by CoronelBuendia** [comment]
Hi @bielsnohr, I think I used to use that aeons ago in BLUEPRINT. I haven't checked if it is used, but if it is it would be in the codebase as all our stuff is at the moment. Happy for you to do a PR!
