### ISSUE TITLE
Lack of robustness combining "offset_clipper" and "make_mixed_face"

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#237]
In GitLab by @DarioV86 on Sep 10, 2021, 09:40

Error faced in `test_firstwallCAD.py` that might show some problems in using pyclipper.
`firstwallCAD.py` failed at line 90 (`face = make_mixed_face(loop)`) by passing a loop that apparently did not show any problem. The passed loop is the top divertor, after the offset. The "twin" loop, the bottom divertor, although it looks identical, it does not give the same problem.
Just a speculation, but this problem seems to occur only with DEMO-DN configuration (STEP seems to be fine), where, due to the "fat" equilibrium shape, at the divertor entrance, the angle formed between first wall and divertor leg is more acute. To corroborate this hypothesis, increasing the gap between x-point and inner wall, the formed angle is less acute and `test_firstwallCAD.py` does not fail.![MicrosoftTeams-image__10_](/uploads/6e226501ead1c9cf9ad0af07a9cab305/MicrosoftTeams-image__10_.png)

![MicrosoftTeams-image__9_](/uploads/b66cb767b817a13a9fe8f302f13fbfb4/MicrosoftTeams-image__9_.png)

![MicrosoftTeams-image__8_](/uploads/8b5061b97c135a1c791c37a3f6f08c50/MicrosoftTeams-image__8_.png)

![MicrosoftTeams-image__7_](/uploads/f2655e815e11ad2e84a7bb25e486c4a9/MicrosoftTeams-image__7_.png)

**Comment by je-cook** [comment]
As neither of these functions exist anymore, the files dont either and we cant see the images, closing
