### ISSUE TITLE
Discuss & resolve whether we want to update geometry parametrisations in-place within optimisations, or if we want to return an optimised copy.

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#2415]
## Description

At present, when we run a geometry optimisation, the `GeometryParamterisation` instance is updated in-place _and_ we return a reference to it in the `GeomOptimiserResult`.

In my view, we should not be editing the input geometry, instead taking a copy and updating that. We would not expect an array to be updated in-place in a normal optimisation.

However, we can't currently implement this, as `OptVariables` objects are not copyable, hence neither are `GeometryParameterisation`s. `PictureFrame`s are also not copyable. Work is happening on #1739 that will solve this issue, so we can proceed with this after that (if people agree it's the right thing to do).

This should be a straightforward change to implement, just a `deepcopy` call at the start of the `optimise_geometry` function.

**Comment by CoronelBuendia** [comment]
I think it makes sense to take a deep-copy of the parameterisation and return the modified one, as you say.

**Comment by je-cook** [comment]
A copy is returned in the new interface
