### ISSUE TITLE
Trapezoidal prism current source doesn't provide a warning when an invalid shape is created

### ISSUE THREAD

**Issue by kj5248** [Fusion-Power-Plant-Framework/bluemira#2592]
## Describe the bug

1)

When using the trapezoidal current source certain combinations of upper angle, lower angle and side lengths results in invalid shapes such as in the figure below. When this happens no warning is published in the terminal.

![invalid_shape](https://github.com/Fusion-Power-Plant-Framework/bluemira/assets/115085094/51573121-ac38-4170-adad-0853ab96bbb4)

2)

Additionally the calculation of the magnetic fields when the angles exceed pi/2 deviate from what would be expected by the prism shape. For example with upper and lower angles of 3pi/4 the shape looks identical to pi/4 however the magnetic fields are different and this should also raise a warning. Below is figure showing discrepency between two identical shapes (angles of 0 or pi) where contour is of difference between the two (ie B1 - B2)

![discrepency](https://github.com/Fusion-Power-Plant-Framework/bluemira/assets/115085094/84cb8e38-3ade-4df3-a748-7498fd4aa4ba)

## Steps to reproduce

To reproduce can run the following code as a script. Will produce the various plots without any warnings being thrown.

```
import numpy as np
import matplotlib.pyplot as plt
from bluemira.magnetostatics.trapezoidal_prism import TrapezoidalPrismCurrentSource
from bluemira.utilities.plot_tools import Plot3D
source = TrapezoidalPrismCurrentSource(
    np.array([0, 0, 0]),
    np.array([0, 0, 2]),
    np.array([1, 0, 0]),
    np.array([0, 1, 0]),
    0.5,
    0.5,
    np.pi * 2 / 4,
    np.pi * 2 / 4,
    1e6,
)
ax = Plot3D()
source.plot(ax=ax)
plt.show()
source2 = TrapezoidalPrismCurrentSource(
    np.array([0, 0, 0]),
    np.array([0, 0, 2]),
    np.array([1, 0, 0]),
    np.array([0, 1, 0]),
    0.5,
    0.5,
    np.pi * 0 / 4,
    np.pi * 0 / 4,
    1e6,
)
source3 = TrapezoidalPrismCurrentSource(
    np.array([0, 0, 0]),
    np.array([0, 0, 2]),
    np.array([1, 0, 0]),
    np.array([0, 1, 0]),
    0.5,
    0.5,
    np.pi * 4 / 4,
    np.pi * 4 / 4,
    1e6,
)
ax = Plot3D()
x = np.linspace(-2, 2, 30)
y = np.linspace(-2, 2, 30)
xx, yy = np.meshgrid(x, y)
zz = np.zeros_like(xx)
bx, by, bz = source2.field(xx, yy, zz)
bx2, by2, bz2 = source3.field(xx, yy, zz)
B = np.sqrt(bx**2 + by**2 + bz**2)
B2 = np.sqrt(bx2**2 + by2**2 + bz2**2)
source2.plot(ax=ax)
source3.plot(ax=ax)
ax.contourf(xx, yy, B-B2, zdir="z", offset=0.0, cmap="magma")
plt.show()
```

## Resolution

Potential solution to 1) would be to test whether the planes of the upper and lower rectangles intercept after the shape is created and if they do raise an error. For 2) either raise warnings when other angles are used (maybe with tests for these cases) or alter how the angles are used in the magnetostatics calculations so that when it goes outside the valid range it is moved (ie pi -> 0).

**Comment by CoronelBuendia** [comment]
I hate to add fuel onto the fire which I then have to deal with, but I've just noticed that the trapezoidal prism stuff takes angles in [rad] on the user-facing API, whereas we've agreed to take angles in [degrees] across the board, no exceptions...

**Comment by kj5248** [comment]
Ah good to know. I should probably change that in the work I've been doing then as well

**Comment by CoronelBuendia** [comment]
Yes, I think in your PolygonalPrism or w/e it is called you can use degrees from the getgo. For this guy sadly it means a user-facing API change, so need to discuss how to proceed with @je-cook

**Comment by je-cook** [comment]
I would consider it taking radians as a bug because of our enforcement of degrees so therefore I'm ok with that change which is probably fixing the API instead of breaking it
