### ISSUE TITLE
Improve parameter name 'separatrix' for RippleConstrainedLengthGOP

### ISSUE THREAD

**Issue by bielsnohr** [Fusion-Power-Plant-Framework/bluemira#2719]
## Description of issue / requirement to address

As discussed in a catch-up meeting, the [`RippleConstrainedLengthGOP`](https://bluemira.readthedocs.io/en/develop/autoapi/bluemira/builders/tf_coils/index.html#bluemira.builders.tf_coils.RippleConstrainedLengthGOP) takes in a `separatrix` as one of its arguments but in fact it is the LCFS (last close flux surface) that is the more likely use case. For internal comprehension, we have renamed the objects passed to this parameter to be `lcfs` in our project, but then the call signature might cause confusion because `separatrix=lcfs` will make developers/users wonder what it should actually be.

## Proposed solution

Rename the input parameter of `RippleConstrainedLengthGOP` from `separatrix` to something more general like `ripple_path` or `ripple_wire`.

## Alternative solutions

Go more specific and rename `separatrix` to `lcfs`.

Another option discussed in the meeting was passing the appropriate object (`BluemiraWire` or `Coordinates`) to the `RipplePointSelector` directly and getting rid of `separatrix` altogether. However, @CoronelBuendia mentioned that he had thought of this, but it has implementation problems with dynamic classes being instantiated (please correct me if inaccurate on that point).

## Additional context

All solutions will involve an API breaking change, so it should probably go in a major release version like @je-cook mentioned.

**Comment by CoronelBuendia** [comment]
@je-cook I've tagged this as milestone v2.0.0 because it breaks API, but I am not personally fussy about when this comes in.
