### ISSUE TITLE
Re-add auto control=False for passive coils from eqdsk

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#2724]
## Description of issue / requirement to address

Since the move of control to a coilset concept instead of a coil concept it has not been possible to automatically read in passive coils as uncontrolled from an EQDSK (and actually broken until #2721)

## Proposed solution

Something like this:

```python
class CoilSet(CoilGroup):
    ...
   @classmethod
    def from_group_vecs(cls, ...):
        self = super().from_group_vecs(...)
        self.control = self.get_coiltype(CoilType.NONE).name
        return self
```

_Originally posted by @je-cook in https://github.com/Fusion-Power-Plant-Framework/bluemira/issues/2721#issuecomment-1767906102_

## Alternative solutions

None considered

**Comment by OceanNuclear** [comment]
Proposed solution almost works: `super()` works with `classmethod` with no issues, I have confirmed this. However,
I'm testing it using `examples/equilibria/Spherical*.py` and python complains of `max_len = max(all_len)`: `ValueError: max() arg is an empty sequence` in `bluemira/equilibria/coils/_grouping.py:486`. I'll look into this after lunchtime.
