### ISSUE TITLE
Shape parametrization: Settup all at once

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#274]
## Description of issue / requirement to address

The current shapes setting use in TF coils is setting the parameters one by ones, and the consistency of the shape tested each time. Hence an artificial shape error can be triggered on the intermediate step of setting the shape, causing some troubles.

## Proposed solution

The solution is to set the shapes parameters all at once using a dictionnary, for instance, triggering the consistency check only once on the genuine shape.

## Alternative solutions

Another way around is to deactivate the checks on the intermediate shape constructions, and activate once the final parameter is set. But it potentially opens the door to unchecked shapes.

## Additional context

Will potentially block next STEP releases.

**Comment by CoronelBuendia** [comment]
This relates to old BLUEPRINT parameterisations which STEP should soon no longer be using... closing
