### ISSUE TITLE
Papercut: Effective charge was given in A.M.U. instead of e.

### ISSUE THREAD

**Issue by OceanNuclear** [Fusion-Power-Plant-Framework/bluemira#2854]
## Describe the bug
Very minor issue: effective charge unit should be ['e'](https://en.wikipedia.org/wiki/Elementary_charge), not 'a.m.u.'.
Found in files `plasma_physics/collisions.py` and `plasma_physics/rules_of_thumb.py`.

**Comment by CoronelBuendia** [comment]
Isn't this because $`Z_{eff} = \frac{1}{n_e} \sum_j n_j Z_j^2`$ making the units [e^2] or something weird? Appreciate [amu] may not be right, and certainly could do with clarity on what Z_eff is because a quick search reveals (to me) there are different ways of defining it and it is in fact a term used in other fields of physics differently?

**Comment by OceanNuclear** [comment]
Just looked over it - thanks for catching this, turns out it should be dimensionless instead. Which makes more sense given that in the equation, it was being added to a dimensionless number 2.

(Full investigation below:

The [full equation](https://wiki.fusion.ciemat.es/wiki/Effective_charge_state) hides away the factor of $Z_{eff}$ in the denominator using $n_e=\sum\limits_i (n_i Z_i)$

I'm not just quoting fusion wiki either; this formula is confirmed by [various](https://pure.tue.nl/ws/portalfiles/portal/3453486/79281.pdf) [sources](https://iopscience.iop.org/article/10.1088/1361-6587/ab6b4a).

Initially I thought Z has unit [e], which makes the formula to have dimensionality = [e] on the left. However, the way they freely interchange $Z_i$ with $n_e$ it becomes obvious that both are dimensionless. Therefore the logical conclusion is, both $Z$ and $n_e$ are both dimensionless integers describing the ratio to the fundamental charge [e]; while $Z_{eff}$ can be a rational number as this ratio to [e] as it now expresses the average charge, but it is still only a ratio, i.e. dimensionless.
)
