### ISSUE TITLE
Bump `matplotlib` to 3.8.0 to tackle invisible `suptitle`

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#2976]
## Describe the bug
A fix for a [problem with `suptitle` in the `matplotlib`](https://github.com/matplotlib/matplotlib/pull/25255) package has been merged in v3.8.0. We are still using 3.7.3.

## Steps to reproduce
Create a figure and attempt to add a `suptitle`.

## Expected behaviour
Vide link.

**Comment by je-cook** [comment]
we can't because python3.8 is not supported. This will come in when #2887 gets merged
