### ISSUE TITLE
Part Wire needs a specific ordering to reconstruct wire using deserialise_shape

### ISSUE THREAD

**Issue by OceanNuclear** [Fusion-Power-Plant-Framework/bluemira#3037]
# Expected behaviour

Start point == start point of the first edge,
end point == end point of the last edge.
i.e. 
`BluemiraWire.start_point() == BluemiraWire.edges[0].start_point()`
`BluemiraWire.end_point() == BluemiraWire.edges[-1].end_point`

# Actual behaviour

Start point == start point of the LAST edge,
end point == end point of the FIRST edge.
i.e.
`BluemiraWire.start_point() == BluemiraWire.edges[0].start_point()`
`BluemiraWire.end_point() == BluemiraWire.edges[-1].end_point`

# Example/Steps to reproduce
Loading the [divertor face wire](https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/b886666947ac76bc067de47a3b223f3de571d178/examples/radiation_transport/data/divertor_face) to examine.
## Screenshots / Tracebacks
![image](https://github.com/Fusion-Power-Plant-Framework/bluemira/assets/26902225/3adc951e-c2c7-48e8-b5fa-afa4e1580db3)
![image](https://github.com/Fusion-Power-Plant-Framework/bluemira/assets/26902225/d771bf35-94d6-4e95-9e46-81baf691a690)
![image](https://github.com/Fusion-Power-Plant-Framework/bluemira/assets/26902225/fa794902-68ac-41c3-bd03-19b604b7465c)
![image](https://github.com/Fusion-Power-Plant-Framework/bluemira/assets/26902225/a28c0646-e3c0-4cc9-b6f4-ca81a3a90842)

# Explanation
This is because `BluemiraWire.shape.Edges` is sorted in reverse order, for reasons unclear to me.

## Proposed solution
In _freecadapi::start_point and _freecadapi::end_point, Wrap the `obj.Edges` inside the `Part.sortEdges` function (and then unpack by indexing to [0]), before indexing to [0] and [-1] as before, respectively.

## Note
I guess this means freecad's API uses memory in a weird/unpythonic way where lists are not ordered by default?

**Comment by OceanNuclear** [comment]
This underlying issue seems to also plague BluemiraWire.value_at. It's worth looking into the example file I've provided.

Or it could be an issue with deserialize_shape/serialize_shape.

**Comment by je-cook** [comment]
There is also shape.OrderedEdges. either way on the whole you shouldn't have to use any freecad api to do this

**Comment by je-cook** [comment]
I would also wager it may come from deserialising the wire

**Comment by je-cook** [comment]
After looking into this it seems like all the edges are reconstructed correctly by the deserialiser but when combined the shape created is not as expected. This could be down to a number of things but my guess is that it may be effected by #1347 and will be very hard to isolate until that is closed
