### ISSUE TITLE
Clean up enum-ification PR

### ISSUE THREAD

**Issue by OceanNuclear** [Fusion-Power-Plant-Framework/bluemira#3042]
## Describe the papercut

PR #3021 can be cleaned up further, by removing the original error messages, as they now become redundant.

Examples can be found in [equilibrium.py](https://github.com/athoynilimanew/bluemira/blob/773020bde30e0a5d5db16edf4692c4f9afedccfc/bluemira/equilibria/equilibrium.py#L1078) and [geometry/](https://github.com/athoynilimanew/bluemira/blob/773020bde30e0a5d5db16edf4692c4f9afedccfc/bluemira/geometry/tools.py#L730)[toosl.py](https://github.com/athoynilimanew/bluemira/blob/773020bde30e0a5d5db16edf4692c4f9afedccfc/bluemira/geometry/tools.py#L740)

## Expected behaviour

No duplicate error messages in code.

**Comment by je-cook** [comment]
closed by #3036
