### ISSUE TITLE
New split psi plotting option

### ISSUE THREAD

**Issue by clmould** [Fusion-Power-Plant-Framework/bluemira#3080]
Expand diagnostic capabilities for equilibria optimisation by adding new plotting option with psi split by contribution.
Figure should include:

- separate plots of the plasma and coilset contribution to psi, for a given equilibrium, in the XZ-plane.
- the location of the LCFS overlaid on each plot.

This plotting option should be available for a given equilibrium object.
This plotting option should be available to display during an optimisation, updated at each iteration.

(Issue copied from Gitlab)

**Comment by je-cook** [comment]
Merged into feature branch #3338
