### ISSUE TITLE
Put together an initial EU-DEMO build procedure

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#309]
## Description of issue / requirement to address

Using the new `Component`, `Parameter` and `geometry` infrastructure we have put into place over the past few months, we need to establish an as-complete-as-possible build procedure for an indicative EU-DEMO device. Much like was done in BLUEPRINT and MIRA.

This involves writing implementations of many design activities (e.g. running PROCESS, shaping TF coils, design optimisation of PF system and equilibria, etc.).

![image](https://user-images.githubusercontent.com/26097289/150839007-8cc0fe53-e1b4-4600-91da-5820c32961d6.png)

## Proposed solution

Implement the proposed calculation logic in a once-through approach, following the black lines in the image above.

## Alternative solutions

This is intrinsic to the nature of the code.

## Additional context
This will form the starting point of the EU-DEMO design pipeline.

The code to generate the above image is here: https://gist.github.com/CoronelBuendia/2a196584334a87b57e042c4625327045

you must first `pip install pyxdsm` before running `python full_reactor_xdsm.py`

**Comment by CoronelBuendia** [comment]
@DanShort12 @ivanmaione @jmorris-uk @je-cook @hsaunders1904 , as discussed earlier today

**Comment by je-cook** [comment]
As https://github.com/Fusion-Power-Plant-Framework/bluemira/issues/1073#issuecomment-1298308864 says there is a branch currently being worked on for this: [hsaunders1904/eudemo_reactor](https://github.com/Fusion-Power-Plant-Framework/bluemira/tree/hsaunders1904/eudemo_reactor)

**Comment by je-cook** [comment]
This has now been completed, at least in the initial state
