### ISSUE TITLE
Problems with new VSCode setting to remember Python interpreter for project

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#3251]
## Describe the bug
In my understanding one of the latest updates from VSCode made the "Python Interpreter" setting to be remembered and automatically retrieved when the project is opened.

**The first issue**: this has modified some environment variables in terminals running in the `bluemira` environment, for example `$HOST="x86_64-apple-darwin13..."`, instead of being equal to the output of `hostname`. This is apparently a [known issue with conda](https://github.com/conda/conda/issues/7031).

As a potential fix, I have tried to [set a `.vscode/.zshenv`](https://github.com/conda/conda/issues/7031#issuecomment-1793127780) to enforce the proper value for `HOST`. But this is overwritten by the activation of the mamba environment, that happens after sourcing `.zshenv`.

**The second issue**: to remedy that situation, I have set a `.../activate.d/fix_host.sh` file as a mamba [post-activation script](https://stackoverflow.com/questions/34606196/create-a-post-activate-script-in-conda). However, due to this new VSCode setting for the Pythonf Interpreter, the mamba environment is apparently never properly activated, so the post-activation scripts are never run. In fact:
```
(bluemira) ... > mamba deactivate
Run 'mamba init' to be able to run mamba activate/deactivate
and start a new shell session. Or use conda to activate/deactivate.
```
and
```
(bluemira) ... > conda deactivate
CondaError: Run 'conda init' before 'conda deactivate'
```
so it looks like `conda/mamba init` are skipped.

I have opened an [issue for VSCode](https://github.com/microsoft/vscode-python/issues/23350).

## Steps to reproduce
See above.

## Environment
- OS: macOS 14.4.1
- Branch: (any)

**Comment by je-cook** [comment]
we are not vscode therefore not for our issue tracker

**Comment by tplobo** [comment]
[temporary solution](https://github.com/microsoft/vscode-python/issues/23350#issuecomment-2097746670)
