### ISSUE TITLE
Add more tests for radiation source model: advective_transport

### ISSUE THREAD

**Issue by kj5248** [Fusion-Power-Plant-Framework/bluemira#3329]
From issue #3212. Add more tests for advective_transport.py. Current breakdown of functions within file that are tested (in test_advective_transport):

ChargedParticleSolver
- [x]  flux_surfaces
- [x] _check_params
- [x] _process_first_wall
- [x] _get_arrays
- [x] _make_flux_surfaces_ob
- [x] _make_flux_surfaces_ib
- [x] _clip_flux_surfaces
- [x] analyse
- [x] _analyse_SN
- [x] _analyse_DN
- [x] _q_par
- [x] plot
- [x] _make_params

**Comment by je-cook** [comment]
On this one, its common practice to not test private methods directly but through the interface to it, ie for DN/SN a switch probably needs to be changed and then a test run again
