### ISSUE TITLE
Does psi and jtor need to be reinited in Equlibrium

### ISSUE THREAD

**Issue by oliverfunk** [Fusion-Power-Plant-Framework/bluemira#3576]
https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/616967bfa4e0db1942b6219f190763dd104db570/bluemira/equilibria/equilibrium.py#L1191

**Comment by geograham** [comment]
This is in the reset_grid function. The psi is already reset to the new grid size but jtor is not (and should be). However, I am closing this issue as it would be more useful to be able to reset the grid for a eqdsk file before creating an Equilibrium object  - to avoid memory problems when creating an equilibrium from an eqdsk with a very large, fine grid. See  #3658.
