### ISSUE TITLE
Kallenbach option DivertorHeatFluxModel

### ISSUE THREAD

**Issue by oliverfunk** [Fusion-Power-Plant-Framework/bluemira#3578]
https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/616967bfa4e0db1942b6219f190763dd104db570/bluemira/codes/process/model_mapping.py#L984

**Comment by je-cook** [comment]
the model has gone from process so the todo just needs removing

**Comment by OceanNuclear** [comment]
Can confirm - for future reference, Kallenbach is removed from process (see [the divertor heat flux model page](https://ukaea.github.io/PROCESS/eng-models/divertor/)), I'll remove it now.
