### ISSUE TITLE
Implement a CSVWriter build stage

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#359]
## Description of issue / requirement to address

There is a requirement to be able to write out generic geometry objects in CSV format.

## Proposed solution

Implement a build step to write a provided component (or potentially geometry object) to CSV based on a discretisation of the underlying wires.

- Inputs: component path
- options: file prefix, file path, comments / metadata

See #356

**Comment by je-cook** [comment]
to close out this issue I think we just need to add the csv writer function in the linked PR to utilities/tools.py
