### ISSUE TITLE
Divertor grazing angle inconsistency

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#368]
## Description of issue

For shallow divertor angles the separatrix curvature radius may generate some additionnal intersection before the expected impact point on the divertor tiles. This is problematic and it may be preferential to avoid it.

## Proposed solution

If the separatrix (or any other selected flux line) intersects the divertor plane before the parametrized target the following actions can be done
1. Increasing the poloidal plane tilt angle until having no intersection (little optimization)
2. Decrease the size of the divertor plate (straight line) until avoiding the unwanted intersection (little optimization)

Option 1 is probably the most robust, but ends up with an increased tilt angle while the second option preserve the tilt angle but may not always provided the expected result and probably leads to more complex divertor target shapes (non straight).

## Example 

Here, you can see that the divertor target angle is at 1 deg as expected, but that the separatrix curvature makes it cross before.

![image](https://user-images.githubusercontent.com/55831357/138290260-8b87b771-0bcf-488f-8293-543594be3292.png)
Figure 1: inboard divertor configuration. The expected target is defined by the intersection between the divertor wall shape (black line) and the divertor KoZ (green line). We can see the collision happends before the difertor target.

![image](https://user-images.githubusercontent.com/55831357/138290147-56799601-6725-445a-b526-18a2df64325d.png)
Figure 2: inboard divertor configuration, zoom at the expected target location. The expected target is defined by the intersection between the divertor wall shape (black line) and the divertor KoZ (green line). We can observe the divertor target actually have the expected angle.

Best regards     
Seb

**Comment by je-cook** [comment]
Although this may still be the case, it will be an issue solved in the reactor design not bluemira's core, closing
