### ISSUE TITLE
Simplified plasmas side TF shape

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#369]
## Description of issue

Due to some missing space on the toroidal direction, the outer leg casing must start at a larger radius than the joint separation. This feature will be probably kept as the un cassed section may be a good proxy for the TF coil joint location (see Issue xx).

An issue with this feature is that it makes the plasma side limit of the coil relatively complex (corners) and hard to offset with small thicknesses. Figure 1 shows the corner that probably upsets the offset :

![image](https://user-images.githubusercontent.com/55831357/138299752-66cd1831-a968-4e0e-90b8-82b100dc1767.png)
Figure1 : top part of a rounded picture frame coil with the leg casing and conductor region. We can obseve the corner. 

Another thing that would be also handy would be to have an TF palsma side loop providing the delimitation of the coil

## Proposed solution

Produce in the 2D coil geometry two Loops (or whatever will be used to replace it)
1. A plasma side TF coil loop made of the WP/conductor loop with the outboard casing subtracted.
2. A simplified plasma side loop that takes a straight line between the inboard casing and the CP. Similar to the blue line in FIgure 2.

![image](https://user-images.githubusercontent.com/55831357/138303552-23848f13-2ff2-4f25-bcb5-4743ec12c7a9.png)
Figure 2: Zommed in version of the figure 1.

This will probably ease a lot the generation of the TS from the TF coil shape.

Best reagards       
Seb

**Comment by CoronelBuendia** [comment]
I think this is a STEP builder specific issue, closing as I reckon it should live in a separate repo.
