### ISSUE TITLE
Making in vessel PF space

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#372]
## Description of issue / requirement to address

It is not easy to make some space for the in-vessel shape at the moment.

## Proposed solution

There is a function in `SegmentedThermalShield` that does this space allocation, internally. The idea would be to make it an external tool/function to be also used to define divertor Keep out zones.

**Comment by CoronelBuendia** [comment]
I think this is a STEP builder specific issue, closing as I reckon it should live in a separate repo.
