### ISSUE TITLE
SN and DN FW clean-up

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#423]
## Description

A lot of little issues found in the review.

- [x] Stop using psi to define the flux line spacing to define the heat flux flux line. This effectively remove `fw_dpsi_n_near` `fw_dpsi_n_far` input. Check with @helen-brooks and @CoronelBuendia if this is all right for them.
- [x] `fw_dx_omp` and `fw_dx_imp` are effectively initial gaps at mid-plane, please rename them as something like `g_pl_fw_omp_init`.
- [x] Replace `fw_p_sol_near` and `fw_p_sol_near` by the separatrix power variable (already exists I think) and a power fraction for the far SOL (`fw_f_pow_far`).
- [x] Remove the "SN" "DN" input on the FW class (they are already setup by choosing which class we are using)
- [x] The in/outboard mid-plane gaps between the separatrix and the first wall are already defined in some ways in PROCESS and **must** be used as initial guess for `fw_dx_omp` and `fw_dx_imp` (or its renamed version). Check if these thicknesses exists under another name in BLUEPRINT and use it. Should ne considered as a gap. If not existing please link these variables to the PROCESS radial build value. `fw_dx_omp` and `fw_dx_imp` corresponds to `scraplo` and `scrapli`, respectively.
- [x] Connect the FW thicknesses variable 'tk_fw_out' and 'tk_fw_in' to their PROCESS conterparts: `fwoth` and `fwith`
- [x] Check if the varibles in `config.py`, in the FW classes does corresponds. If not, allign them.
- [x] `fw_psi_init` present in `FirstWallDN` but not in `config.py`, do you want remove it from `FirstWallDN` or add it on `config.py`?
- [x] Implement the remaining comments in https://github.com/Fusion-Power-Plant-Framework/bluemira/pull/413
- [ ] Add a test where the divertor is built from the KoZ. Motivation: the refactor broke this functionality on the way, better test it.

The last bit is fairly important, I think.

Dependent on: https://github.com/Fusion-Power-Plant-Framework/bluemira/pull/413

Best regards      
Seb

**Comment by je-cook** [comment]
Done or no longer part of bluemira core but moved to the reactor designers
