### ISSUE TITLE
`make_divertor_target` SOL and PFR swaping

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#432]
## Describe the bug

The SOL and PFR divertor targets length parametrization are often swaped. 

## Steps to reproduce

Run SPR-017 (or probably any STEP designs).

## Expected behaviour

We expect the PFF length to size the PFR and the SOL to size the SOL.

## Background

The tangeant to the separatrix loop is determined in the `get_tangent_vector` function, using loop point indexes. This makes the process dependent on the way the loop indexes are setup. As I understand (plz check and correct me if I am wrong @DarioV86) the tangeant is defined using the separatix point and the  closest n-1 point. In case of different order the notion of PFR and SOL as well as the angle are swapped.

This issues is partly soleved by changing the angle of the rotation and swapping the SOL and PFR point *a posteriori*. This is all good but the length needs swapping too there, hence the bug as it is not done with the current logic.

## Proposed solution

Swap the points **before** the target length are set. In addition the swapping can be performed with a rotation of 180 deg using the strike point as centre for the rotation.

Hope this solves the observed issues !

Best regards      
Seb

**Comment by je-cook** [comment]
This function no longer exists and the work itself would be contained in a reactor design divertor designer/builder
