### ISSUE TITLE
Divertor shape adaptation for SPR-022

### ISSUE THREAD

**Issue by DarioV86** [Fusion-Power-Plant-Framework/bluemira#457]
The SPR-022 divertor shape has some issues due to the available space in the divertor region.
In the previous firstwall.py version, that I used to provide a first wall shape to other groups, I fixed the problem.
The new version, does not include this change.
Hopefully, it would be enough to have a SPR-022 first wall profile, but there might be additional problems due to the space.

**Comment by je-cook** [comment]
After our rearchitecture this is part of a reactor design not bluemira core
