### ISSUE TITLE
Add bluemira feature roadmap to REAMDE.md

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#480]
## Description of issue / requirement to address

We've discussed that going open source is unlikely to change our day to day, because we will not immediately have users. I still think it would be useful (even if it is just for us) to have a feature roadmap on the repository, clearly exhibited, e.g. in the README.

## Proposed solution

Add a graphic for a feature roadmap for the code, listing out things that we plan on delivering more or less in chronological order, without any dates. I don't have any preconceptions of what this graphic should look like. A Gantt chart could work I suppose.

## Alternative solutions

Keep it all in our heads with probably some inconsistencies between us.

## Additional context

We could use the TSVV-14 plan, but perhaps we want to be a little more granular and a little less vague.

**Comment by jmorris-uk** [comment]
![Roadmap_Q1_2022](https://user-images.githubusercontent.com/46964268/146942573-c8c38b9d-cd46-48d1-b348-b209ffd76b88.png)

As discussed in last weekly meeting, draft roadmap for Q1-Q4 2022.

@CoronelBuendia @DanShort12 @je-cook @ivanmaione @fabrizio-franza @kunbim 

Let me know if you have any comments.

**Comment by CoronelBuendia** [comment]
Thanks for this James, I guess looking at this fresh I'm wondering what else might fall into the "Core" category, next year or in future.

I think that "adapt 3-D CAD routines" will just get done along-side the implementation of the EU-DEMO workflow, as we're doing for the TF and PF coils. I know we split this out into two deliverables for TSVV-14, but now that we're on it, it seems strange.

I think we need to put running PROCESS through its Python API on this. I have a lot of hope that will make things much easier in the medium term. Again, don't know if that is core or feature.

Perhaps in Q3 you can put "Structural beam FE solver", or similar. I'm waiting until the geometry dust settles before porting over the old BLUEPRINT solver for potential use in TF shape optimisation.
