### ISSUE TITLE
FW power fraction reformulation for double null

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#498]
## Description of issue

The current power sharing in the FW and the particle flux power sharing as 4 fraction. 
Power conservation however sets the fractions sum must be one.

This is done through a posteriori test.

## Proposed solution

A much better way is to only have for fraction and no test *a posteriori* test:
- `f_sol_top`: To/bottom power fraction (the sum of the inboard and the outboard divetor leg)
- `f_sol_in_top`: fraction of the energy flowing to the top that goes on inboard
- `f_sol_in_bot`: fraction of the energy flowing to the top that goes on inboard

Remove the test that is now fulfulled by definition.

Best regards     
Seb

**Comment by je-cook** [comment]
Power sharing on the firstwall is covered in a firstwall designer and is not implicit in core bluemira any more, closing and complete
