### ISSUE TITLE
Environment encoding sometimes set implicitly to ASCII instead of utf8

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#504]
## Describe the bug

UnicodeEncodeError when running EUDEMO_reactor.py

## Steps to reproduce

1. Run script EUDEMO_reactor.py

4. See error:

```python
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
~/code/bluemira/examples/design/EU-DEMO/EUDEMO_reactor.py in <module>
     53 
     54 with open(f"{get_bluemira_root()}/examples/design/EU-DEMO/template.json", "w") as fh:
---> 55     json.dump(params, fh, indent=2, ensure_ascii=False)
     56 
     57 config = {

~/miniforge3/envs/bluemira/lib/python3.8/json/__init__.py in dump(obj, fp, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    178     # a debuggability cost
    179     for chunk in iterable:
--> 180         fp.write(chunk)
    181 
    182 

UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 1: ordinal not in range(128)
```
## Expected behaviour

The script should run or mock or read PROCESS and make an initial reactor.

## Environment (please complete the following information)

- OS: Ubuntu 18.04
- Branch: develop

**Comment by je-cook** [comment]
Narrowed it down to 1 line [here](https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/00e082e94514d2cea0dbb68c92ed2cbdb6632044/bluemira/display/auto_config.py#L57)

Its something to do with PySide with app line used to be a context manager I thought too...

**Comment by je-cook** [comment]
Ok its a pyside bug which is fixed by the most recent pyside version (5.15.2 on pip) which is not available at the moment on conda-forge. I see no way around the bug unless we update pyside.
Because we're on conda it restricts us quite forcefully to versioning so maybe the time to try and go pure pip (or maybe poetry?)

**Comment by CoronelBuendia** [comment]
Hmm.. OK, and we can't just pip pyside, taking it out of conda-forge because of FreeCAD, I guess?

**Comment by je-cook** [comment]
It didnt seem to work when I tried that last month, but I will double check at some point this week

**Comment by je-cook** [comment]
Not seen in a long time, will reopen if it reappears
