### ISSUE TITLE
Coil ordering not preserved when reloading eqdsk

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#509]
## Describe the bug

It seems that coil ordering isn't preserved when loading an eqdsk from file.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Using the below script:

```python
from bluemira.base.file import get_bluemira_root
from bluemira.equilibria.equilibrium import Equilibrium

root = get_bluemira_root()
fp_orig = f"{root}/data/BLUEPRINT/reactors/EU-DEMO/equilibria/EU-DEMO_eqref.json"
dir_new = f"{root}/generated_data/BLUEPRINT/reactors/EU-DEMO/equilibria"
fn_1 = "EU-DEMO_eqref_test1.json"
fp_1 = f"{dir_new}/{fn_1}"
fn_2 = "EU-DEMO_eqref_test2.json"
fp_2 = f"{dir_new}/{fn_2}"

print(f"reading {fp_orig}")
eq = Equilibrium.from_eqdsk(fp_orig)
print(f"writing {fp_1}")
eq.to_eqdsk(directory=dir_new, filename=fn_1)
print(f"reading {fp_1}")
eq = Equilibrium.from_eqdsk(fp_1)
print(f"writing {fp_2}")
eq.to_eqdsk(directory=dir_new, filename=fn_2)
```

2. Note that the coilset sections of the eqdsk are different between the first and second output files.

## Expected behaviour

The coilset should be created in the same order that it's written.

## Environment (please complete the following information)

- OS: Ubuntu 20.04 (WSL2)
- Branch (if developing) matti/eq-read-write-bug (see #503)

**Comment by je-cook** [comment]
No longer true for json or eqdsk
