### ISSUE TITLE
Plasma profiles not scaled to Ip at runtime

### ISSUE THREAD

**Issue by alexanderianblair** [Fusion-Power-Plant-Framework/bluemira#511]
## Describe the bug

Plasma currents obtained by integration over the toroidal currents, as calculated directly from the `psi`, `ffprime` and `pprime` profiles in .`eqdsk` and `.json` outputs in `FIESTA,` are inconsistent with the output plasma current `cplasma` reported in the same files.

This may be because scaling to maintain the total plasma current is applied directly to the toroidal plasma currents in Bluemira, rather than the `ffprime` and `pprime` profiles, which are left unchanged after initialisation in a `CustomProfile` object.

Bluemira appears to use the total plasma current to rescale toroidal currents at every calculation of `jtor`, so otherwise remains self-consistent from provided inputs.

## Expected behaviour

Total plasma current in output data should be self consistent between the reported value and those calculated directly from psi and profile data.

**Comment by CoronelBuendia** [comment]
The issue with the output files was fixed in #512 but we could still do with scaling the profiles in-place during run-time
