### ISSUE TITLE
Generalise interface for run_systems_code

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#518]
## Description of issue / requirement to address

Currently we look for a configuration key `"process_mode"` in run_systems_code to determine the run mode. As part of the generalisation of some of the bluemira design/build logic, we are looking to nest configuration for each build stage. As such it would be cleaner to align on a common `"mode"` key within each design stage for which a run mode is relevant.

e.g. the following:

```python
build_config = {
    ...,
    "process_mode": "run",
   ...,
}
```

Would become:

```python
build_config = {
    ...,
    "PROCESS": {
        ...,
        "mode": "run",
        ...,
    },
    ...,
}
```
## Proposed solution

Modify the `run_systems_code` interface to look for the `build_config` as supplied for the relevant design stage. The run mode would then be determined by the `mode` key within that config, and we could also simplify the rest of the `process.Run` interface to just take in the `params` and the subset of the `build_config` for that stage.

## Alternative solutions

We can work around this by translating the nested config values into the flat values needed for the current PROCESS interface (and probably will do this in the short term).

## Additional context

Not assigning this, but @je-cook - might be relevant or worth discussion for the external codes interfacing work that is on-going?

**Comment by je-cook** [comment]
Covered in #427 (although there is a temporary workaround to smooth uptake). Does anything else need to happen?

**Comment by DanShort12** [comment]
Yep, this is good with the latest changes.
