### ISSUE TITLE
Strategy for avoiding circular imports

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#533]
## Description of issue / requirement to address

We have quite a lot of cases now where it is easy to introduce circular imports and have collectively spent quite a bit of time resolving cases where they do get introduced. I'm putting this in as a place to collect some thoughts on how we might improve that. Some points of reference:

- We have some cases where inter-dependent functionality are quite far apart, so these should probably be brought together.
- In some cases we have imports that are only used for type hinting. There are some strategies to resolve this (using `TYPE_CHECKING` to only run the imports if a type checker is running), and we should get in the habit of applying these.
- In my experience most of the circular imports boil down to loading something in a `__init__.py`. I personally like being able to see the module for an import when it's being used, but perhaps removing these imports and importing from the module may help in the short term.

## Proposed solution

To be discussed.

## Alternative solutions

To be discussed.

**Comment by je-cook** [comment]
I've had a little go at doing some of this. I dont know how to get round the flake issues though see  #549   tests pass locally
