### ISSUE TITLE
Radiation model

### ISSUE THREAD

**Issue by DarioV86** [Fusion-Power-Plant-Framework/bluemira#602]
## Description of issue / requirement to address

Add models to calculate the radiation source term from a `Equilibrium` and a set of impurities and radiative loss functions:
* Core radiation (1-D PROCESS core radiation but extrapolated to 2-D, see https://www.sciencedirect.com/science/article/pii/S0920379615302891 and https://doi.org/10.13182/FST11-A11650)
* SOL radiation (2-D model based on the two point model, see https://iopscience.iop.org/article/10.1088/0741-3335/39/6/001 and http://data.lib.hutech.edu.vn/mucluc/d456afd00c0e17e699ebb904ac38de19.pdf)

## Proposed solution

* Implement the aforementioned models in the `radiation_transport` module.
* As a first pass, do not implement as a base `Solver` class
* Extract the flux surface "access" presently in `AdvectiveTransportSolver` and move in to a new utility class, that is used in both `AdvectiveTransportSolver` and `SOLRadiationTransportSolver` (future PR)

## Proposed API

Inputs:
* `Equilibrium`
* Impurity radiative loss functions from ADAS (use PROCESS for now)
* Parameters:
 * Impurities concentrations (from PROCESS)
 * Separatrix power
 * Transmission sheath coefficient (e.g. 25 eV)
 * Hydrogen ionisation temperature
 * Ideal detachment temperature for the target
* Problem settings (gaussian/exp decay, etc.)

Outputs:
* Radiation source term as an array based on a set of points OR a set of psi_norm values
* Radiation source term (including core and SOL contributions) as a function (disgestable by CHERAB - needs investigation, potential need to interpolate)

Try and maintain the same API (in terms of methods) for the core and SOL radiation models

Updated following discussion:

```python
# User-facing solver should include core and SOL source terms
solver = RadiationSourceTermSolver(parameters, eq: Equilibrium, *args, **kwargs)

# Calculate source term at specific input points
radiation_at_points = solver.calculate_source_at_points(x: np.ndarray, z: np.ndarray)

# Calculate source term at specific psi_norm values
points, radiation_at_points = solver.calculate_source_at_psi_norm(psi_n: np.ndarray)
```
We discussed that for this PR the latter interface should be sufficient, when I get back in September I can start on the refactor to remove use of `ChargedParticleSolver` inside the radiation source term solver, possible adding the calculation of a source term at the specified points.

**Comment by je-cook** [comment]
closed by #2224
