### ISSUE TITLE
Images showing geometry parameterisations

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#607]
## Description of issue / requirement to address

We currently only show the variables for a geometry parameterisation as text in the code. It would be good if we had a way to generate annotated plots of the parameterisation so that it is easy to see what the different variables correspond to.

## Proposed solution

Implement a function on the `GeometryParameterisation` class that can generate an annotated plot of the parameterisation with the variables shown. Include a custom sphinx directive to call this when we generate the documentation.

## Alternative solutions

We could manually make equivalent plots, but they could be less easy to maintain.

**Comment by je-cook** [comment]
Some work towards this in #1287
