### ISSUE TITLE
STEP FW build crash

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#610]
## Describe the bug

First wall does not find outboard baffle end a second time after https://git.ccfe.ac.uk/step-bluemira-reactor-design/step-blueprint-reactor-design/-/merge_requests/84. 

## Steps to reproduce

Steps to reproduce the behaviour:
pull: https://git.ccfe.ac.uk/step-bluemira-reactor-design/step-blueprint-reactor-design/-/merge_requests/84
Run SPR-008

## Expected behaviour

FW that builds as expected, without errors

## Screenshots / Tracebacks

The FW builds as expected but after the second `make_2d_profile(self)` call, the divertor opening intersection finder `def find_outer_point(point_list, x_compare)` crashes as it fails to select the outer intersection as `point_list`, containing the end of the baffle containts only one point the second time list.

This seems to be related to the use of generator in `find_outer_point`.

``` bash
-------------------------------------------------------------------------+
| Designing a double-null (DN) first wall                                 |
+-------------------------------------------------------------------------+

point : -6.983180234599717
norm : 2
loop : 2-D closed ccw x-z Loop, 135 long
compare_x : 2.5311508616605125
inner : False
cut_plane : <BLUEPRINT.geometry.geombase.Plane object at 0x7f7e0d993af0>
plane_ints : [[ 2.13115086  0.         -6.98318023]
 [ 3.03115086  0.         -6.98318023]]

point : -6.983180234599717
norm : 2
loop : 2-D closed ccw x-z Loop, 209 long
compare_x : 2.5311508616605125
inner : False
cut_plane : <BLUEPRINT.geometry.geombase.Plane object at 0x7f7e0c1cdaf0>
plane_ints : [[ 2.13114981  0.         -6.98318023]]
+-------------------------------------------------------------------------+
| ERROR: FAILED: build_FW_system                                          |
+-------------------------------------------------------------------------+
Traceback (most recent call last):
  File "/home/skahn/step-blueprint-reactor-design/step_reactor/debug.py", line 17, in wrap
    return func(*args, **kwargs)
  File "/home/skahn/step-blueprint-reactor-design/step_reactor/builders.py", line 740, in build_FW_system
    self.FW.build()
  File "/home/skahn/bluemira/BLUEPRINT/systems/firstwall.py", line 1180, in build
    input_x = self.x_all_ints
  File "/home/skahn/bluemira/BLUEPRINT/systems/firstwall.py", line 1341, in make_2d_profile
    self.params.tk_fw_out,
  File "/home/skahn/bluemira/BLUEPRINT/systems/firstwall.py", line 389, in make_divertor
    # Pick some flux loops to use to locate strike points and shape the
  File "/home/skahn/bluemira/BLUEPRINT/systems/firstwall.py", line 117, in get_intersection_point
    point_on_loop: [float,float]
  File "/home/skahn/bluemira/BLUEPRINT/systems/firstwall.py", line 66, in find_outer_point
    return next(filter(lambda p: p[0] > x_compare, point_list))
StopIteration
```

**Comment by DanShort12** [comment]
Just as a note on this, a generator will raise an `StopIteration` error whenever it reaches the end of the iterable - even if that iterable has effectively zero length. As an example the following will execute the same values as many times as you want (always returning 6):

```python
next(filter(lambda val: val > 5, [4, 5, 6]))
```

While the following will always error because it's trying to get the next value of a generator formed from an empty iterable:

```python
next(filter(lambda val: val > 5, [1, 2, 3]))
```

Looking at the original error here, I suspect the second run of `make_2d_profile` was encountering a scenario where there were no points outward of whatever value was assigned to `x_compare` at the time. I see this has been fixed by removing the second call, but figured worth noting in case anyone comes back to this to look at fixing the root cause (either not using a generator in that function, or handling the `StopIteration` error in the function that calls it). @sebkahn @je-cook

P.S. I think you can actually see this condition in the print out above:

- The first call has the following, so presumably the `find_outer_point` logic gets the second `plane_ints` element:

```python
compare_x = 2.5311508616605125
plane_ints = [[2.13115086, 0. -6.98318023], [ 3.03115086, 0., -6.98318023]]
```

- The second call has the following, so there are no longer any `plane_int` values with a first element that is larger than `compare_x`, which will raise a `StopIteration` error when the next value is extracted from the generator:

```python
compare_x = 2.5311508616605125
plane_ints = [[2.13114981, 0., -6.98318023]]
```

**Comment by sebkahn** [comment]
> Just as a note on this, a generator will raise an `StopIteration` error whenever it reaches the end of the iterable - even if that iterable has effectively zero length. As an example the following will execute the same values as many times as you want (always returning 6):
> 
> ```python
> next(filter(lambda val: val > 5, [4, 5, 6]))
> ```
> 
> While the following will always error because it's trying to get the next value of a generator formed from an empty iterable:
> 
> ```python
> next(filter(lambda val: val > 5, [1, 2, 3]))
> ```
> 
> Looking at the original error here, I suspect the second run of `make_2d_profile` was encountering a scenario where there were no points outward of whatever value was assigned to `x_compare` at the time. I see this has been fixed by removing the second call, but figured worth noting in case anyone comes back to this to look at fixing the root cause (either not using a generator in that function, or handling the `StopIteration` error in the function that calls it). @sebkahn @je-cook
> 
> P.S. I think you can actually see this condition in the print out above:
> 
>     * The first call has the following, so presumably the `find_outer_point` logic gets the second `plane_ints` element:
> 
> 
> ```python
> compare_x = 2.5311508616605125
> plane_ints = [[2.13115086, 0. -6.98318023], [ 3.03115086, 0., -6.98318023]]
> ```
> 
>     * The second call has the following, so there are no longer any `plane_int` values with a first element that is larger than `compare_x`, which will raise a `StopIteration` error when the next value is extracted from the generator:
> 
> 
> ```python
> compare_x = 2.5311508616605125
> plane_ints = [[2.13114981, 0., -6.98318023]]
> ```

Hi @DanShort12, many thanks for the explanaition on generators and these function syntax that confused me a little I must admit.

I understand now the issue is that no intersections are found between the horizontal plane at X-point and the second first wall on the second call, although this sould not be called twice anymore, I am still unsure on why this should happend.

Do you have any comments @DarioV86 on the potential cause of absence of intersection?

PS: This is no longer a blocking issue.
