### ISSUE TITLE
BLUEPRINT systems to use bluemira Component

### ISSUE THREAD

**Issue by DanShort12** [Fusion-Power-Plant-Framework/bluemira#65]
**Is your feature request related to a problem? Please describe.**
When #63 has been merged, we will be able to start moving BLUEPRINT systems to use `Component` rather than `ReactorSystem`.

**Describe the solution you'd like**
Existing BLUEPRINT systems will be migrated to use `Component`.

**Describe alternatives you've considered**
This is the agreed direction for the bluemira implementation. The alternative would be to fully update the BLUEPRINT systems to use the full reactor tree architecture, but this is a stepping stone towards that state, rather than performing one big bang change.

**Comment by CoronelBuendia** [comment]
Think it's fair to say this is no longer the plan, @DanShort12 ?
