### ISSUE TITLE
Generalize the Optimization class to any statistical problem

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#688]
## Requirement to address

After a very nice review on the Optimization problem re-factor done by @alexanderianblair, it appeared that Sensitivity analysis, Incertainty propagation and data exploration (sampling) are all sharing very similar structures. They all need
- A list of input with variation bounds
- A figure of merit
- They potentially include constraints

A potential generalization is hence possible.

## Proposed solution

It may be good to have a StatisticProblem parent class from which the Optimizer/Optimizer problem classes are child. With for example a sensitivity analysis class linked with sampling algorithm from the SALib (https://salib.github.io/SALib/) library.

Best regards

Ref: @alexanderianblair, @CoronelBuendia

**Comment by CoronelBuendia** [comment]
Seems gratuitous to me... What's the motivation? There are obvious similarities between these mathematical techniques, what I'm missing is a reason for us to try and generalise to something for which we have no present use (or near-term future use - as far as I can tell). We're not writing an optimisation library, ML library, UQ library, etc.

As mentioned a few months ago, you can always use external libraries in combination with some BLUEMIRA functionality in a script for whatever your needs are.
