### ISSUE TITLE
bluemira installation in ZSH

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#699]
## Issue

When installing bluemira in a Mac that uses zsh in Terminal, a couple of commands noted in the installation instructions do not properly run:

1. In the "install-conda.sh" script, the following command:
`envsubst '$HOME' < conda/miniforge-init.sh > ~/.miniforge-init.sh`
produces a "command cannot be found" error.
I have resolved this issue by installing "gettext" with Homebrew, as suggested [here](https://stackoverflow.com/questions/23620827/envsubst-command-not-found-on-mac-os-x-10-8).

2. In the installation instructions in the documentation, the following command:
`python -m pip install --no-cache-dir -e .[dev]`
cannot be used if escape characters are not applied to the square bracket characters:
`python -m pip install --no-cache-dir -e .\[dev\]`
as suggested [here](https://github.com/mu-editor/mu/issues/852).

Perhaps this information could be added to the documentation.

## Environment

- OS: MacOS Monterey
- Version 12.2

**Comment by je-cook** [comment]
For the first, I will get on it

For the second it seems we have an inconsistency between the README and the docs. The README version works for me (on zsh too): `python -m pip install --no-cache-dir  -e .'[dev]'` 

I will change the docs
