### ISSUE TITLE
Removing shape parametrization default values

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#727]
## Description of issue

Default values have caused some issues in the past for STEP reactor as it cause unexpected behaviour. At best the code crashes and you know there is an issue. The worst case scenario is when the unknown defaut value bias the optimization problem without you knowing it.

`GeometryParameterisation` child classes all have default values for their 
`BoundedVariable`, and it has provent in the past a problematic feature.

Code snipet
``` python 

    def __init__(self, var_dict=None):
        variables = OptVariables(
            [
                BoundedVariable(
                    "x1", 4, lower_bound=2, upper_bound=6, descr="Inboard limb radius"
                ),
                BoundedVariable(
                    "x2",
                    14,
                    lower_bound=10,
                    upper_bound=18,
                    descr="Outboard limb radius",
                ),
                BoundedVariable(
                    "dz",
                    0,
                    lower_bound=-0.5,
                    upper_bound=0.5,
                    descr="Vertical offset from z=0",
                ),
            ],
            frozen=True,
        )
```

## Proposed solution

Get rid of the `BoundedVariables` default values and use directly `var_dict` to set them, that becomes non-optional.

Of course the keys have then to be checked and the relavant error message should be sent.

The error message could contain proposed values for the defauts to help the user setting them if he is in trouble doing so.

**Comment by je-cook** [comment]
this is essentially covered by #2396 at least now its accessible what the defaults are from scripting.

**Comment by je-cook** [comment]
In addition I see the main reasoning behind this is because some parameterisations don't have any constraints (eg `PictureFrame`) which can lead to some odd shapes from optimisation. 

We could add a check for non violation on constraints on `create_shape`. 
@ajpearcey you might want to look into adding constraints to the `PictureFrame` parameterisation.

I'll have a think about the violation suggestion above and close on that if we do it.

**Comment by kj5248** [comment]
All parameterisations now use var_dict for default values so the original issue is resolved. The need for parameterisations to have constraints will be set up as another issue and is linked here #3112.
