### ISSUE TITLE
Routine `regenerate-ipynb-examples` fails during commit

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#743]
## Describe the bug

The pre-commit routine `regenerate-ipynb-examples` fails and aborts the commit (vide screenshot).
The commit works when using `SKIP=regenerate-ipynb-examples git commit -a`.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Attempt to commit.

## Screenshots / Tracebacks

![Screenshot 2022-02-23 at 09 27 30](https://user-images.githubusercontent.com/40567154/155295149-71cf96c9-2c82-451c-8afa-23c391c9c664.png)

## Environment (please complete the following information)

- OS: macOS
- Version 12.2.1
- Branch: tplobo/BoP_example (in fact, all under tplobo)

**Comment by je-cook** [comment]
Branches I've checked 

- `tplobo/installation`, `tplobo/material_steam` runs fine ipynb check fails as it should on existing uncommented examples 
- `tplobo/BoP_example` for me runs fine but I see that the notebook files were converted with python 3.10.2 not 3.8.12 ? Ive downloaded 3.10.2 to check if its a version issue and the converter works on newer python and it seems to work fine...

git diff snippet (among others):
```diff
diff --git a/examples/BLUEPRINT/base/base_tutorial.ipynb b/examples/BLUEPRINT/base/base_tutorial.ipynb
index 0fb5889f..c8e503f4 100644
--- a/examples/BLUEPRINT/base/base_tutorial.ipynb
+++ b/examples/BLUEPRINT/base/base_tutorial.ipynb
@@ -213,7 +213,7 @@
       "name": "python",
       "nbconvert_exporter": "python",
       "pygments_lexer": "ipython3",
-      "version": "3.8.12"
+      "version": "3.10.2"
     }
   },
   "nbformat": 4,
```

I'm a bit stumped

**Comment by je-cook** [comment]
environment issue with git manager (the pre-commit command needs python>3.6 to run aliased to `python`)

**Comment by tplobo** [comment]
To ensure the git manager will run git commands within any given active conda environment, the git manager GUI should be opened from a Terminal running the environment.

For example: if using VSCode to open the environment, run `stree` from within VSCode after installing the SourceTree Command Line Tools.
