### ISSUE TITLE
Allow merging into branches that are not develop and main

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#780]
## Description of issue / requirement to address

It isn't currently possible to merge branches into a long lived feature branch without the tests passing and being approved. We should consider allowing this to happen has its restricts development on branches that can collect parts of features into a single PR

## Proposed solution

Only block merge on test fail and un reviewed when merging in develop and main

## Alternative solutions

N/A

## Additional context

It makes it harder to interact with external collaborators trying to add features (see ukaea_powerbalance branch)

**Comment by DanShort12** [comment]
Strange, I thought we only had those restrictions on protected branches (develop / main) but perhaps something wasn't quite right in the config there. Definitely agree that people should be able to merge into feature branches regardless of checks.

**Comment by je-cook** [comment]
It seems its just that it needs to be approved by someone other than the submitter I think

**Comment by CoronelBuendia** [comment]
@je-cook did you say yesterday that this was fixed now?

**Comment by je-cook** [comment]
yeah seemingly
