### ISSUE TITLE
Primitive BluemiraWire [0,1] interpolation and point-finding

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#799]
## Description of issue / requirement to address

We need a way to interpolate a `BluemiraWire` in a purely primitive form, not relying on discretisation.

We need to access a point:
* at a given length along the wire [0.. wire.length]
* at a given parameterised length along the wire [0.. 1]

## Proposed solution
Add a `value_at` method to `BluemiraWire`

## Alternative solutions
Some functions in geometry/tools.py

## Additional context

_Originally posted by @CoronelBuendia in https://github.com/Fusion-Power-Plant-Framework/bluemira/pull/680#discussion_r817911738_

This functionality would already be useful in a couple of places, namely above and also in parameterised PF coil positioning along a wire.

**Comment by ivanmaione** [comment]
I would propose adding to BluemiraWire the function `def value_at(self, alpha:float, length:float = None) -> point(np.array)` with alpha in range [0,1] and length in range [0, self.length] using the native `valueAt` FreeCAD function of Edge.

**Comment by CoronelBuendia** [comment]
Agreed on the name, not sure about the signature though. Might ping you about this at some point in the week depending on workload. I'd also like to write this issue a bit better :D... was a quick one.

**Comment by CoronelBuendia** [comment]
as discussed with Ivan: ```def value_at(self, alpha: Optional[float] = None, distance: Optional[float]=None) -> Coordinates:```
