### ISSUE TITLE
Add "display" attribute to `Parameter` class, to allow user to select units in applied to plots, tables and diagrams

### ISSUE THREAD

**Issue by tplobo** [Fusion-Power-Plant-Framework/bluemira#853]
## Description of issue / requirement to address
When running each particular module, a user might be tempted to individually convert each parameter value into preferred units for plots, tables or diagrams; e.g. power flows in the Power Cycle displayed in MW instead of W.

## Proposed solution
Centralize this feature in the `Parameter` class, so that it can be used by every module, a new set of attributes should be created:
- **display**:           what is stored in `value`, but transformed to the units in `display_unit`
- **display_unit**:   units desired in plots, tables or diagrams

Ideally:
- the implementation should include a starting value of `None` in `default_unit`, so that no transformation is applied as a default.
- each module modifies internally the settings for default units for each parameter, that should only be applied during its own run.

**Comment by CoronelBuendia** [comment]
To be discussed in our next weekly

**Comment by tplobo** [comment]
Issue description update.

## Description of issue / requirement to address
This feature should be initially only implemented in the Power Cycle. Later analysis can establish whether it should be implemented in a more higher-level class, accessible from every module.

## Proposed solution
Implement a dedicated JSON input file, exclusive to the Power Cycle module, that establishes preferences in terms of units for tables, diagrams and plots. Apply unit conversion in each particular data-visualization method, based on these inputs.

**Comment by je-cook** [comment]
This is covered by the use of `param.value_as(<unit>)` when creating various outputs and doesnt need to be part of the Parameter object. 

Outputs of specifics like that are usually created by the reactor designer and they have control over what they output and how they do it.

We can obviously add customisation options to plots we set up to enable unit changes. 
Something similar to this could be revisited in the future if there is a concrete useful example but for now it feels extra complexity for no immediate benefit.
