### ISSUE TITLE
bug on bluemira.codes.plasmod.api.Solver

### ISSUE THREAD

**Issue by ivanmaione** [Fusion-Power-Plant-Framework/bluemira#869]
## Describe the bug

bluemira.codes.plasmod.api.Solver is not implemented correctly.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Run 'examples/codes/run_plasmod_example.py'
4. See error `TypeError: Can't instantiate abstract class Solver with abstract methods get_raw_variables`

## Expected behaviour

run Plasmod

## Screenshots / Tracebacks
-
## Environment (please complete the following information)

- OS: Ubuntu 20.04.2 LTS
- Branch [develop]

## Additional context

-

**Comment by ivanmaione** [comment]
@je-cook could you please give a look to this problem?

**Comment by je-cook** [comment]
yep on it
