### ISSUE TITLE
Equilibrium q profile loader/calculation issue

### ISSUE THREAD

**Issue by sebkahn** [Fusion-Power-Plant-Framework/bluemira#896]
## Describe the bug

There is a discrpancy between the way `q` profile is loaded trhough the EQ object and the EQDSK reader reading FIESTA output files.

Observed discrepancy

![image](https://user-images.githubusercontent.com/55831357/161044610-189b11d8-edcf-4c9d-b156-752c6f906988.png)

## Steps to reproduce

The following script is run to make the above plot

``` python
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

from bluemira.equilibria.file import EQDSKInterface
from bluemira.equilibria import Equilibrium

# Define tested file
file_path = str(Path(Path.home(), "step-blueprint-reactor-design", "SPR-045", "4", "Inputs", "SPR45_ISD1_AH.geqdsk"))

# Load via eqdsk reader
reader = EQDSKInterface()
reader_dict = reader.read(file_path)

# Get reader qpsi and psi from 0 to 1
qpsi_reader = reader_dict["qpsi"]
qpsi_size = len(qpsi_reader)
psi = np.arange(qpsi_size) / float(qpsi_size)

# Plot qpsi reader
fig, ax = plt.subplots()
ax.plot(psi, qpsi_reader, '-r', label="Reader load")
ax.set(xlabel=r"$\psi_\mathrm{N}$", ylabel=r"$q_\psi$")

# Load via Equilibrium object
EQ = Equilibrium.from_eqdsk(file_path, load_large_file=False)
qpsi_EQ = EQ.q(psi)

# Plot qpsi Equilibrium
ax.plot(psi, qpsi_EQ, '-b', label="EQ load")
ax.set(xlabel=r"$\psi_\mathrm{N}$", ylabel=r"$q_\psi$")

# Add legend
ax.legend()

fig.canvas.draw()
plt.show()
```

The following STEP file will be provided privately if UKAEA user.

## Expected behaviour

Both profiles are expected to the exactly the same!

**Comment by CoronelBuendia** [comment]
Please send me the file and I will take a look. I'm hoping it's a psi V.s vs. V.s/rad convention issue, but hard to say. Is there anything different about this equilibrium w.r.t. to previous ones? Do the plasma current and toroidal field still both "turn" clockwise as seen from above?
