### ISSUE TITLE
params not being passed into Reactor in EU-DEMO example

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#901]
## Describe the bug

It seems the that config dict that I thought was being passed into the reactor is not changing the parameters being used by the reactor.

## Steps to reproduce

Steps to reproduce the behaviour:

1. Using script examples/design/EUDEMO/EUDEMO_reactor.py
2. Run command: ```config = {
    "tk_sol_ib": 0.2,
}```
and the rest of the script
4. Note output of ```reactor.params.tk_sol_ib = 0.225```

## Expected behaviour

I expect the parameters being fed into the reactor to overwrite the default values in the Configuration

## Screenshots / Tracebacks

If applicable, add screenshots / tracebacks to help explain your problem.

## Environment (please complete the following information)

- OS: [e.g. Ubuntu 18.04]
- Version [e.g. 0.0.x]
- Branch (if developing) [e.g. develop]

**Comment by DanShort12** [comment]
I think this is being picked up by the mock PROCESS file (which has `tk_sol_ib` and `tk_sol_ob` set to 0.255). What PROCESS mode are you running in?

**Comment by CoronelBuendia** [comment]
ah crap, probably just mock. that makes sense then, sorry.
