### ISSUE TITLE
Add EU-DEMO ports for RM scheme

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#906]
## Description of issue / requirement to address

We need to have ports into the vacuum vessel to allow in particular for remote maintenance of the in-vessel components.

This requires a small reduced model to calculate in a crude way some of the IVC kinematics (in particular for the blanket segments). This should be used to create exclusion zones for the position of the PF coil positioning routine.

The ports should also be included in the CAD models of the VV, thermal shield, cryostat, and radiation shield.

## Proposed solution
Add a routine to calculate the size of the upper and lower ports based on remote maintenance considerations.

Add build stages for the ports to update the VV, thermal shield, cryostat, and radiation shield components

## Alternative solutions

N/A

**Comment by je-cook** [comment]
Ports added see #1896
