### ISSUE TITLE
Add in-vessel component segmentation for RM scheme

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#907]
## Description of issue / requirement to address

We need to segment the in-vessel components in such a way that they may be extracted from the vacuum vessel via the ports.

## Proposed solution

Add build stages for the blankets and divertors, segmenting them as per RM requirements and the ports sizes (see #906 )

## Alternative solutions

A few different segmentations possible.. we'll start with the simplest one.

**Comment by oliverfunk** [comment]
Initial stages implemented, and improvements to continue in due course.
