### ISSUE TITLE
Proposal: `debug_naughty_geometry` decorator

### ISSUE THREAD

**Issue by CoronelBuendia** [Fusion-Power-Plant-Framework/bluemira#929]
## Description of issue / requirement to address

I'm always frustrated when a geometry operation fails with a `FreeCADError` and sometimes it can be a pain to recreate that geometry in order to understand better why the operation failed.

I thought it would be nice to have a decorator that stashes the failed operation in such a way that it is possible to inspect the state of affairs after the fact. I think it's likely we're going to get a lot of issues raised on geometry operations as they can be temperamental. So it would be nice to facilitate bug-reporting and debugging.

## Proposed solution

I've just used the following because I needed a failing offset in order to write a test, and it looks like it could be made into a useful decorator for some badly behaved geometry operations.

```python
    try:
        return BluemiraWire(
            cadapi.offset_wire(wire._shape, thickness, join, open_wire), label=label
        )
    except Exception as e:
        import json
        import os
        from bluemira.base.file import get_bluemira_path
        from datetime import datetime
        wire_dict = serialize_shape(wire)
        fp = get_bluemira_path("naughty_geometry", subfolder="generated_data")
        name = "offset_wire"+str(datetime.now())
        fn = os.sep.join([fp, name])

        with open(fn, "w") as file:
            json.dump(wire_dict, file, indent=4)
        raise e
```
Obviously, you'd want to capture the input arguments in the JSON as well.

Thoughts @ivanmaione @je-cook @hsaunders1904 ?

**Comment by je-cook** [comment]
Yeah that sounds promising. It could be nice to more generally have some debugging functionality that gets automatically enabled when in the debug loglevel. This and maybe a few other tools could be made to plot things, save things etc

**Comment by hsaunders1904** [comment]
Sounds like it could be helpful. Just to be clear, is this a utility that will be used whilst we're debugging, or are we going to add the decorator permanently to badly behaved operations?

**Comment by CoronelBuendia** [comment]
I'd err on the side of just having a decorator on some operations that are known to behave badly... I don't want to create too much work for ourselves in terms of logging etc., we've got a lot on our plate already!

**Comment by CoronelBuendia** [comment]
I'd leave them in though, perhaps with a message that says that the failed operation was stashed in a naughty_geometry folder :)

**Comment by ivanmaione** [comment]
I like the idea. Probably, on the side, we have to test a little bit more (or write better) the serialize/deserialize function (I just wrote it with the aim to be used for the mesh creation and, probably, not all the properties for a complete debug of geometry objects are exported).
