### ISSUE TITLE
Move existing solvers to new interface

### ISSUE THREAD

**Issue by hsaunders1904** [Fusion-Power-Plant-Framework/bluemira#956]
## Description of issue / requirement to address

Following #928, the existing solvers should be updated to comply to the new `SolverABC` interface.

The solvers to update are:

- `FileProgramInterface`
- `plasmod.solver`
- `process.solver`

**Comment by je-cook** [comment]
dependent on what happens first probably also #789

**Comment by CoronelBuendia** [comment]
Had a go at making a solver from scratch (without rearranging too much of what was already lying around)... #707
