### ISSUE TITLE
Consider TOML as an alternative to JSON for input file formats

### ISSUE THREAD

**Issue by je-cook** [Fusion-Power-Plant-Framework/bluemira#996]
## Description of issue / requirement to address

It can be useful to have comments inside you input files that are not related to the input file itself. The JSON spec doesnt allow comments (although jsonc does it would require a new dependency) whereas TOML does

## Proposed solution

Replace JSON files with TOML files

## Alternative solutions

Continue to use JSON files

**Comment by oliverfunk** [comment]
Considered but at the moment JSON seems to fit our use case better.
